### ISSUE TITLE
Suggestions for landscape-bot

### ISSUE THREAD

**Issue by hugovk** [landscapeio/landscape-issues#100]
The PR commenting bot is working well so far!

Some wording/formatting suggestions. Currently, it comments a bit like this:

> The overall code health score did not change when comparing wordnik 35a73b6 on hugovk/word-tools to master 57fd6b0 on hugovk/word-tools
> 
> No new problems were introduced
> No problems were fixed
> 
> View the changes on Landscape.io

Coveralls comments like this:

> Coverage remained the same when pulling 35a73b6 on wordnik into 57fd6b0 on master.

How about using similar wording for no changes? It makes it easier to scan the page, and also neutral wording ("remained the same") may be better suited than negative wording ("did not change"). 

Also end each sentence with a full stop and use bullets for the other lines:

> The overall code health score remained the same when comparing wordnik 35a73b6 on hugovk/word-tools to master 57fd6b0 on hugovk/word-tools.
> - No new problems were introduced.
> - No problems were fixed.
> 
> View the changes on Landscape.io.

Thanks!

**Comment by carlio** [comment]
All good suggestions, thank you - I've implemented all of them :+1:
