### ISSUE TITLE
Add possibility to specify detect-requirements path

### ISSUE THREAD

**Issue by evilaliv3** [landscapeio/landscape-issues#102]
Currently if a project is structured to have the source code of the application in a nested directory (e.g., [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) landscape fails to detect the dependencies.

e.g. on https://landscape.io/github/globaleaks/GlobaLeaks/6/modules/backend/globaleaks/handlers/collection.py you can notice all the errors 'Exception doesn't inherit from standard "Exception" class' that are due to the fact that landscape do not detect the requrements.txt file that is inside the nested directory backend.

to solve this issue it would be interesting to implement a detect-requirements-path directive inside .landscape.yaml in order to specify the path to be used by the [requirements-detector](https://github.com/landscapeio/requirements-detector)

**Comment by carlio** [comment]
Hi @evilaliv3 , I added a setting to the `.landscape.yaml` file called `requirements`, which allows you to list one or more files that Landscape should use for finding requirements. The [docs page](https://landscape.io/pages/docs) has some more information.

**Comment by evilaliv3** [comment]
thanks @carlio ! it's working great! https://landscape.io/github/globaleaks/GlobaLeaks/42
