### ISSUE TITLE
Broken badge for private repository

### ISSUE THREAD

**Issue by mdshw5** [landscapeio/landscape-issues#104]
Landscape.io badges show up just fine on one of my public repositories:

![screen shot 2015-01-06 at 11 42 33 am](https://cloud.githubusercontent.com/assets/819554/5632005/1fb211c6-9599-11e4-982d-62368b283799.png)

``` rst
.. |Landscape| image:: https://landscape.io/github/mdshw5/pyfaidx/master/landscape.svg
   :target: https://landscape.io/github/mdshw5/pyfaidx/master
   :alt: Code Health
```

However, for one of my private repositories I get a broken image (the link still works):

![screen shot 2015-01-06 at 11 44 16 am](https://cloud.githubusercontent.com/assets/819554/5632031/5cf53b3a-9599-11e4-950b-eae62cd2e129.png)

``` rst
.. |Landscape| image:: https://landscape.io/github/mdshw5/gemstone/master/landscape.svg
    :target: https://landscape.io/github/mdshw5/gemstone/master
    :alt: Code Health
```

Any idea if I've done anything wrong? As far as I can tell, each directive is identical except for the repository name. If I try to load the image URL from the rendered Readme.rst on GitHub:

``` bash
$ curl https://camo.githubusercontent.com/3ec5cce72548ada1bb8276e46533ef9543084d8f/68747470733a2f2f6c616e6473636170652e696f2f6769746875622f6d64736877352f67656d73746f6e652f6d61737465722f6c616e6473636170652e737667
Not Found
```

And if I try the image URL directly in my browser I get the correct badge image:

![screen shot 2015-01-06 at 11 49 07 am](https://cloud.githubusercontent.com/assets/819554/5632106/0e0ccf5a-959a-11e4-8308-41a36476ccab.png)

It seems that embedding the URL to the SVG badge for the private repository does not work:

![](https://landscape.io/github/mdshw5/gemstone/master/landscape.svg)
`![](https://landscape.io/github/mdshw5/gemstone/master/landscape.svg)`

While embedding the URL to the SVG badge for the public repository works just fine:

![](https://landscape.io/github/mdshw5/pyfaidx/master/landscape.svg)
`![](https://landscape.io/github/mdshw5/pyfaidx/master/landscape.svg)`

**Comment by carlio** [comment]
Hi @mdshw5 ,

Then problem is that GitHub requests and serves the images itself (that's the camo.githubusercontent thing), and the GitHub 'user' is not logged in to Landscape so cannot see the images.

I think the best way to fix this is to add a kind of API auth token to the URL, which I'll look into implementing later this evening. That way the token can at least be revoked.

**Comment by carlio** [comment]
@mdshw5 : If you look at the [URLs for badges on your private project page](https://landscape.io/github/mdshw5/gemstone/master/badges) you'll see there is a 'badge_auth_token' parameter which will allow non-logged in people (including the GitHub bot) to see the badge.

There's no UI to change or revoke this value yet, so I'll leave the issue open, but will try to get that done over the next day or so.

**Comment by mdshw5** [comment]
Thanks so much for giving this some work. I'll try the token and let you know if it works for me.

**Comment by carlio** [comment]
Great thanks!

**Comment by mdshw5** [comment]
Works great! Thanks for the help on this.
