### ISSUE TITLE
Incorrectly detected syntax for project written in python 3

### ISSUE THREAD

**Issue by pyghassen** [landscapeio/landscape-issues#105]
You system detected a syntax errors on a project written in python, assuming it was in written for python 2 while it is for python 3.

**Comment by pirat89** [comment]
If I am right, python 3 isn't supported yet - issue #32

**Comment by carlio** [comment]
Python3 is implemented now (if detected/configured, see https://blog.landscape.io/python-3-support.html) and is as of today running 3.5.1 so I think this should be working - let me know if not!
