### ISSUE TITLE
As a User I would like to be less confused by email alerts.

### ISSUE THREAD

**Issue by davidmiller** [landscapeio/landscape-issues#106]
Users are easily confused.

> Subject: Deterioration: openhealthcare/opal scored 90%
> 
> Body: 90% 0% Code quality didn't change as a result of this commit.

At a guess you're rounding differently in the email template and the trigger for "Only email me if code quality decreases".

**Comment by carlio** [comment]
This should be fixed now :)

**Comment by davidmiller** [comment]
Awesome sauce :)
