### ISSUE TITLE
Sidebar's FAQ link incorrectly redirects to the Documentation page for anonymous users

### ISSUE THREAD

**Issue by chornsby** [landscapeio/landscape-issues#107]
Log out of your account.
Navigate to the [faq page](https://landscape.io/pages/faq). 
Click on the FAQ link in the sidebar (see picture below).
The user is redirected to the [documentation page](https://landscape.io/pages/docs).

![faq](https://cloud.githubusercontent.com/assets/5579692/5858601/268b4bb8-a25d-11e4-853c-ddfeada9d599.PNG)

Just a small thing but good to know. :+1:

**Comment by carlio** [comment]
Fixed, thanks!
