### ISSUE TITLE
GitHub Status API usage

### ISSUE THREAD

**Issue by carlio** [landscapeio/landscape-issues#108]
GitHub has a status API which is the nice box saying "build failed because of tool X". Landscape should use that! See also #71

**Comment by raghavrv** [comment]
:+1:

**Comment by tofu-rocketry** [comment]
:+1:

**Comment by tilgovi** [comment]
My ideal use of this would involve setting a threshold for score decrease to trigger a fail.

**Comment by tofu-rocketry** [comment]
I think a threshold would a nice additional feature, but, for me, any decrease in quality should be marked as a failure. One can still go ahead and merge a PR with a failed test after judging its possible impact.

**Comment by tilgovi** [comment]
Truth. Sorry to complicate things. Just posting the status API would be amazing.

**Comment by nijel** [comment]
:+1:

**Comment by krmaxwell** [comment]
This would be much better than the current commenting, for sure.

**Comment by amueller** [comment]
+10

**Comment by dopplershift** [comment]
+1

**Comment by public** [comment]
+:100:

**Comment by d0ugal** [comment]
Yeah, I tried the commenting on PR's for a while, but it started to drive me mad. So had to disable it :(

**Comment by jakirkham** [comment]
+1

**Comment by carlio** [comment]
Just released this, from now on it will use the Status API. Comments are now disabled, although you can re-enable them if you like (useful if you want to keep track of changes throughout a PR, as the status is only the "most recent" commit). Let me know if you notice any issues or if it is not updating or anything, cheers!

**Comment by jakirkham** [comment]
Yay! Thanks @carlio. Looking forward to trying this.

**Comment by krmaxwell** [comment]
:tada:
