### ISSUE TITLE
Numeric pylint error display

### ISSUE THREAD

**Issue by mdshw5** [landscapeio/landscape-issues#111]
Error messages should display both long-name and short numeric codes: 

![screen shot 2015-02-12 at 9 43 03 am](https://cloud.githubusercontent.com/assets/819554/6169476/a56f45c6-b29b-11e4-9f3c-08cfaf049dbe.png)

**Comment by ssokolow** [comment]
Agreed.

As a workaround, I've been keeping a terminal open so I can run commands like `pylint --list-msgs | grep unexpected-keyword-arg` whenever I need to pragma away a warning without making the line too long.

**Comment by carlio** [comment]
This has been done for a while, forgot to close this issue.
