### ISSUE TITLE
Checks run twice when creating a PR

### ISSUE THREAD

**Issue by edmorley** [landscapeio/landscape-issues#112]
STR:
1) Push code to a new branch
2) Create a PR for that branch

Expected:
Checks run only once (unless a followup is pushed to the branch etc).

Actual:
Checks are run after both step 1 and step 2.

This causes:
- additional load for landscape.io
- clutter in the recent activity view
- the stats to be wrong on the check after step 2 above, since the "things changed since last run" is compared to the code at step 1, and so shows no change.

For example:
https://landscape.io/github/mozilla/treeherder-service/873
https://landscape.io/github/mozilla/treeherder-service/874

...these are both from the same commit, and yet 874 says no improvement in the score/number of items fixed, unlike 873.

**Comment by carlio** [comment]
This should be fixed now, I'm actually surprised it wasn't a problem earlier! It's not so much the PR/new branch but that two checks could be scheduled if the first one hadn't finished the next time it came to search for new commits. Let me know if you see this happen again, cheers for the report!

**Comment by edmorley** [comment]
Great - thank you :-)
