### ISSUE TITLE
BOT: Delete previous comments when a new comment is added

### ISSUE THREAD

**Issue by raghavrv** [landscapeio/landscape-issues#113]
I think it would be less cluttery if you make the bot to delete all but its latest comment(s)...

**Comment by raghavrv** [comment]
@carlio ping

**Comment by tofu-rocketry** [comment]
Implementing #71 would obviate the need for this.

**Comment by raghavrv** [comment]
@tofu-rocketry Status API looks awesome! I'm closing this in favor of that! thanks

**Comment by ragv** [comment]
@tofu-rocketry But still don't you think having the previous comments deleted would be cleaner (especially since a) the status check notifier thing is not going to come anytime sooner and b) the bot could sometimes be used in conjunction with it ( esp. since the comment by bot will cause a notification unlike the status check thing ). Reopening.

@carlio please share your views on this!

**Comment by raghavrv** [comment]
@tofu-rocketry But still don't you think having the previous comments deleted would be cleaner (especially since a) the status check notifier thing is not going to come anytime soon and b) the bot could sometimes be used in conjunction with it ( esp. since the comment by bot will cause a notification unlike the status check thing ). Reopening.

@carlio please share your views on this!

**Comment by carlio** [comment]
Hi @ragv, 

I suspect this will have to be configurable :) Using only the status API and/or deleting the old comments means you lose some of the intermediate history and I have seem comments on other code checking services saying that is not good! It shouldn't be too hard to implement the comment deletion.

**Comment by ragv** [comment]
Thanks could you also check why we (scikit-learn/scikit-learn) does not get comments from the bot even after enabling the same?

**Comment by raghavrv** [comment]
> It shouldn't be too hard to implement the comment deletion.

Also @carlio does that mean the comment deletion feature will be released soon?

**Comment by carlio** [comment]
It depends on your definition of 'soon' as I'm away on holiday next week and don't really want to ~~anger the beast~~ release a new feature just before I go away. Let's tentatively say before end of March?

**Comment by raghavrv** [comment]
awesome :+1: thanks :)

**Comment by tofu-rocketry** [comment]
GitHub saves the status of all checks for each commit, therefore, so long as you're not squashing commits, you'll have a history. (If you do squash, you're probably not interested in having a full history anyway.)

e.g. Last three commits on this PR: apel/apel#66

**Comment by carlio** [comment]
This is now implemented: the default is to use the status API (so only the "latest commit") but there's an option to keep the old behaviour to get a comment on every push if you want to see the intermediate status.
