### ISSUE TITLE
Documentation: Missing how to globally deactivate a test

### ISSUE THREAD

**Issue by tobias47n9e** [landscapeio/landscape-issues#114]
This page (https://landscape.io/pages/docs) is missing a tutorial for how to globally deactivate a test in the yaml file.

I would like to globally diable the unused-argument warning. Is this the correct line and how can it be included in the yaml file?

`pylint: disable = unused-argument`

**Comment by kylepjohnson** [comment]
I have a similar need to disable certain pylint errors. Is this kind of global disabling possible at all?

**Comment by carlio** [comment]
Hi @kylepjohnson and also @tobias47n9e : 

I'm currently working on a new updated documentation as the current page misses a lot of stuff. It's not quite finished yet but it contains the answer you want:

http://docs.landscape.io/suppressing.html

(If you see any typos or issues please let me know!)

**Comment by carlio** [comment]
Docs are now live so closing this issue.

**Comment by tobias47n9e** [comment]
Thanks!
