### ISSUE TITLE
Score has decreased, but listed files were not modified in that commit

### ISSUE THREAD

**Issue by edmorley** [landscapeio/landscape-issues#116]
For https://landscape.io/github/mozilla/treeherder-service/931/diff

It says the score has decreased, since two new problems were found.

However:
(a) those errors/warnings have existed for ages, so they are not new.
(b) these files were not even modified by that commit

Any ideas? :-)

**Comment by carlio** [comment]
Hi @edmorley, I think this is a bug related to code diffing. I'll have a check and see what `git diff` outputs to verify. Landscape uses the output of `git diff` to match old and new messages.

**Comment by edmorley** [comment]
Same again in https://landscape.io/github/mozilla/treeherder/1222/diff
