### ISSUE TITLE
'uses' plugins not auto-detected

### ISSUE THREAD

**Issue by edmorley** [landscapeio/landscape-issues#119]
In this run I removed the explicitly defined 'uses' property:
https://landscape.io/github/mozilla/treeherder-service/977/modules/.landscape.yaml

Since the docs imply that it should not normally need to be set manually:
https://landscape.io/pages/docs

However the config page:
https://landscape.io/github/mozilla/treeherder-service/977/config

Now displays:
`Uses: Nothing`

**Comment by carlio** [comment]
This was a mis-labelling on the config page, it should have said "not specified" instead of "nothing"...
