### ISSUE TITLE
Bug: "100%" is misaligned in badges

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#12]
When a badge reads 100%, the text is aligned far enough to the right that it's only maybe 1px away from being chopped off by the edge of the image.

My impression is that the text position is defined as a left-alignment using static padding. If so, the simplest solution would be to `len()` the text before drawing it and special-case the alignment for readouts with more than three characters.

**Comment by carlio** [comment]
Fixed! See [100%](https://landscape-io.s3.amazonaws.com/img/badges/landscape_100.png) vs [99%](https://landscape-io.s3.amazonaws.com/img/badges/landscape_99.png)
