### ISSUE TITLE
Link directly to the prospector RTD pages from https://landscape.io/pages/docs

### ISSUE THREAD

**Issue by edmorley** [landscapeio/landscape-issues#120]
The https://landscape.io/pages/docs page lists some of the basic options, however I needed to know:
- What the different medium/high/... strictness levels actually meant
- How to disable pep8/pyflakes, since we run those in our Travis run, so it's not necessary to run them again

To find the answer the the former I had to:
https://landscape.io/pages/docs -> strictness section -> link to prospector repo (https://github.com/landscapeio/prospector) -> link to RTD in the readme (http://prospector.readthedocs.org/) -> realise that the details for each strictness level wasn't under the strictness section, but "profiles" -> click link to profiles page (http://prospector.readthedocs.org/en/master/profiles.html) -> under "built-in profiles" click the link to the full list on github (https://github.com/landscapeio/prospector/tree/master/prospector/profiles/profiles)

And for the latter:
Lots of rummaging around on the propector RTD page, since the http://prospector.readthedocs.org/en/master/supported_tools.html page only lists the command line options. I eventually looked at the built-in profiles (https://github.com/landscapeio/prospector/tree/master/prospector/profiles/profiles) and found this syntax:

```
pep8:
  run: false
pyflakes:
  run: false
```

Please can we deep link to the relevant prospector RTD pages from https://landscape.io/pages/docs and also add some more examples/info to the landscape docs page too?

Thanks! :-)

**Comment by carlio** [comment]
Hi @edmorley, I'm working on a new docs site here: http://docs.landscape.io/ . That has much more information and will be much better at finding information. Please take a look and see what you think. It's still a work in progress (and even has some placeholder links) but please comment on the contents!

**Comment by carlio** [comment]
I'll close this now as the new docs site is up and running.

**Comment by edmorley** [comment]
Sorry for not replying sooner - was on vacation for a fair amount of March and then playing work/email catch up. The docs on https://docs.landscape.io/advanced.html look great and resolve the issue here - thanks!
