### ISSUE TITLE
Can't Set Pull-Request Settings

### ISSUE THREAD

**Issue by JohnMurray** [landscapeio/landscape-issues#122]
Under the settings page, it talks about setting yes/no to run landscape.io on pull requests. However I don't see the setting on the page, just empty where the setting should be:

![settings](http://new.tinygrab.com/c817f4c450f818d866228708d0895eaa22db060de1.png)
http://grab.by/FoiE

**Comment by carlio** [comment]
I'd be very grateful if you could share what browser and plugins you're using. The ticky-boxes are fiddled with by JavaScript to make them look nicer and it seems it only gets half of the way in your case.

(btw if you want me to manually adjust something let me know)

**Comment by JohnMurray** [comment]
Right now I am using Chrome with the following extensions enabled:
- Auto Refresh Plus 
- Coffee Console
- JsonView
- Last Pass
- Momentum
- XKCD substitutions

**Comment by JohnMurray** [comment]
Specific Chrome information:

![Chrome Info](http://new.tinygrab.com/c817f4c450f5e347d91f40eec8b864300601371418.png)

**Comment by d0ugal** [comment]
FWIW, I ran into this issue on mobile safari (iOS 8.3 I think, the latest) today. It looked almost exactly the same with an invisible checkbox.

**Comment by carlio** [comment]
I think this will be fixed now as I've changed which static asset library Landscape uses. I can't be sure as I've never been able to reproduce this, so please re-open if it's still an issue!
