### ISSUE TITLE
I can't make login

### ISSUE THREAD

**Issue by drgarcia1986** [landscapeio/landscape-issues#123]
![login](https://pbs.twimg.com/media/B_h-mgkWEAEAmnq.png)

Response headers:

```
Connection: keep-alive
Content-Type: text/html
Date: Sun, 08 Mar 2015 11:41:58 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
Vary: Cookie
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
x-content-type-options: nosniff
```

**Comment by carlio** [comment]
@drgarcia1986 is this still the case? I think you tried to log in exactly as I was moving everything from Digital Ocean to Linode. Please reopen if it's still a problem

**Comment by drgarcia1986** [comment]
I tried now and received the same error :(
