### ISSUE TITLE
Status of PR bot, triggering it?

### ISSUE THREAD

**Issue by amueller** [landscapeio/landscape-issues#124]
Is there a way to see the status of current running bots for PRs for a specific repo?
Also, when enabling the bot, does it automatically run on all current PRs, or only new ones? If only new ones, is there a way to trigger it on old PRs?

Thanks :)

**Comment by carlio** [comment]
It will only work for new PRs - people complained when it suddenly appeared and commented on 20 old PRs on their project. I can manually kick it for you if you send me the PR numbers.

**Comment by amueller** [comment]
Ok makes sense. I think it should be fine on new PRs only (we have ~200 old PRs).
I opened this right after enabling, but didn't get anything yet: https://github.com/scikit-learn/scikit-learn/pull/4372 Maybe I made a mistake when enabling the comments?

**Comment by carlio** [comment]
I had a look and I found a bug! (CC @ragv because you asked in another issue)

It turns out that if you set the 'comment on pull requests' on the repository but not the entire organisation, then it would never search for new pull requests. I'll fix that...

**Comment by amueller** [comment]
Ok, i'll set it for the organization in the meantime. Thanks for checking.

**Comment by raghavrv** [comment]
> I can manually kick it for you if you send me the PR numbers.

@carlio If its not much trouble, could you trigger it for 4354, 4299, 3907 :p Thanks :)

**Comment by carlio** [comment]
@ragv I just kicked off a check for those three PRs, you should see some comments soon

**Comment by raghavrv** [comment]
@carlio I got comments for those :D thanks :)
