### ISSUE TITLE
passing configuration to pylint

### ISSUE THREAD

**Issue by amueller** [landscapeio/landscape-issues#125]
Is there a way to pass configuration to pylint, like ignoring certain errors?
It is not mentioned in the documentation.

**Comment by carlio** [comment]
Hi @amueller - the new work-in-progress docs site has what you're looking for, see here: http://docs.landscape.io/suppressing.html#ignoring-errors-of-a-certian-type-in-the-whole-project

Also, if you have an existing `.pylintrc` file then it will use that - http://docs.landscape.io/advanced.html#existing-configuration

**Comment by amueller** [comment]
thanks :)
