### ISSUE TITLE
in documentation page, "example" and "link" menu items are dead

### ISSUE THREAD

**Issue by amueller** [landscapeio/landscape-issues#126]
In http://docs.landscape.io/ the menu items at the top go nowhere and should probably be removed?

**Comment by amueller** [comment]
Also, the title says "<no title>" I remember the same issue with sphinx-bootstrap, but I forgot how I fixed it. I think in the newer version is might just be the first title in the page?

**Comment by carlio** [comment]
Yeah those links are just placeholders - I need to do some tidying up before that docs page becomes official. The title of the main page is '<no title>' currently!

**Comment by amueller** [comment]
feel free to close the issue ;)

**Comment by carlio** [comment]
Fixed now!
