### ISSUE TITLE
Server Error on Repository

### ISSUE THREAD

**Issue by mcflugen** [landscapeio/landscape-issues#130]
I've been getting a 500 error on one of my repositories for the last couple days.

https://landscape.io/github/bmi-forum/bmi-babel

My other repositories seem to be working just fine.

**Comment by carlio** [comment]
Hi @mcflugen - seems to be working now. There were a lot of issues due to the GitHub DDoS attack so I'll close this as "probably okay" :)

**Comment by mcflugen** [comment]
Perfect. Thanks! You can upgrade it to "definitely okay".
