### ISSUE TITLE
Why this service requests access to a private email adresses?

### ISSUE THREAD

**Issue by matkoniecz** [landscapeio/landscape-issues#131]
On registration:

> Authorize application
> Landscape.io by @landscapeio would like permission to access your account 
> Personal user data Email addresses (read-only)
> This application will be able to read your private email addresses.

Why not just use public one?

**Comment by carlio** [comment]
Hi @matkoniecz - the email address is needed to send notifications and so on. Most people don't have a public address and the GitHub API is "all or nothing". In the future you'll be able to select which scopes to allow so you could grant everything except email bit, but GitHub has been saying that for more than a year and I can't tell you when it'd be possible!

Some more info: https://docs.landscape.io/githubperms.html

**Comment by LeeNg** [comment]
I'm not a lawyer, so maybe I'm misinterpreting GitHub's requirement, but does this statement, "This application will be able to read your private email addresses.", mean that GitHub has access to my Yahoo account and read all of it's email? If yes, why the need for such intrusion?

**Comment by matkoniecz** [comment]
No, it will be able to see email address (something@something.pl).

Not contents of email inbox.

**Comment by lignumpy** [comment]
So it can't read the contents of an email, but why does it need to read email addresses?

**Comment by carlio** [comment]
In order to be able to send email notifications when checks ran.

No need to worry now though, it's shut down.

**Comment by inuoshios** [comment]
Thanks for this reply, @carlio. 👍

**Comment by Teighe** [comment]
"This application will be able to read your private email addresses" is no longer shut down and I'm also trying to figure out what the scope, use, and limitations of this statement are.
