### ISSUE TITLE
Github hook documentation link incorrect

### ISSUE THREAD

**Issue by wolph** [landscapeio/landscape-issues#133]
When you go to the landscape hook in your repository it links to https://landscape.io/docs/
A permanent redirect would be good regardless, but the link is currently broken so it should be fixed as well.

Steps to reproduce:
1. go to one of your repos on github
2. click the settings button on the right
3. click on the 'webhooks & services' button on the left
4. click on the edit icon next to the Landscape service
5. notice the text: `For more information about Landscape, see https://landscape.io/docs/`

**Comment by carlio** [comment]
I've added a redirect now, thanks! Also the hook documentation will be changed when GitHub merge this PR: https://github.com/github/github-services/pull/1038
