### ISSUE TITLE
Server error when trying to disable bot

### ISSUE THREAD

**Issue by amueller** [landscapeio/landscape-issues#134]
Hi.
I tried to disable the bot here:
https://landscape.io/preferences/repo/github/scikit-learn/scikit-learn/pull-requests
But when I click "save" I get "Server Error (500)".

FYI if you are interested in feedback:
We are disabling the bot as it is "too loud". It posts after each commit (which is sensible). As people often do multiple commits, one after the other, that means that there will 5 or ten posts by the bot for any actual human comment, which make it hard to track the discussion. Also, it generates a lot of notifications.
Travis avoids this by a clever interface, that I guess only works by directly integrating with github.
Having a link to a site with the landscape.io results for each PR might be useful, but having a long list of bot comments doesn't seem to be.

**Comment by carlio** [comment]
Hi @amueller , I just saw the stack trace - it should be fixed now if you want to try again.

Also thanks for the feedback - it's something I get a lot and I'm planning to fix in https://github.com/landscapeio/landscape-issues/issues/108 (by using the same mechanism as Travis as you mention)

**Comment by amueller** [comment]
I still get the 500, but I think the settings were saved.

**Comment by carlio** [comment]
Ok definitely almost certainly probably fixed now.

**Comment by amueller** [comment]
indeed. Thanks :)
