### ISSUE TITLE
Excluding branches

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/landscape-issues#135]
It would be nice if we could exclude some branches (e.g. `gh-pages`). There is no point in you guys checking it if we know it has no Python code.

**Comment by ssokolow** [comment]
...but, at the same time, it'll have to be optional because, sometimes, I'll use the `gh-pages` branch as the master branch for things like repositories of small scripts where it makes more sense for the `.py` files to be mixed into the same folder tree as the website.

**Comment by jakirkham** [comment]
Absolutely, either some web GUI thing or some text for the YAML file (like what Travis does). I'd lean towards the latter, but either would be acceptable.

**Comment by ssokolow** [comment]
I'd prefer the latter too. I maintain a comprehensive exit strategy in case any part of a project's service fabric goes bankrupt or turns evil and the biggest pains in the butt are the things like GitHub Issues and Releases that aren't automatically backed up by the `git pull` cronjobs I run on each project's main and wiki repositories.

**Comment by carlio** [comment]
I solved this the easy way by simply hiding failed checks which happen on branches called `gh-pages`. Feel free to reopen if you think it needs to be more configurable than that!
