### ISSUE TITLE
Add ability to force check updates on branches

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/landscape-issues#137]
Sometimes it appears a commit is missed or at least it isn't associated properly with all branches that now have it. In the event a commit is not checked due to this error, it would be nice to have a force check feature for the repo as a whole.

**Comment by spaceone** [comment]
I would like this feature, too. Sometimes (when doing a fast forced push) the repository is not updated.

**Comment by carlio** [comment]
There's now a "refresh" icon to force a check of the head of whatever branch you're looking at.
