### ISSUE TITLE
Landscape ignores pylintrc

### ISSUE THREAD

**Issue by syabro** [landscapeio/landscape-issues#138]
When I run prospector on local it understand rules from `pylintrc` but landscape.io ignores it.

How can I use it with landscape.io?

I don't want to copy all my rules to .landscape.yaml especially I don't see support of
a) Error messages codes. F.e. `R0904`
b) Regex overwriting. F.e. `const-rgx`

And other useful stuff.

Is it possible to do with landscape.io or should use other tools?

**Comment by carlio** [comment]
Landscape runs prospector so it should be picking up the `.pylintrc` file. I'll investigate why it is not.

**Comment by syabro** [comment]
Thanks!

**Comment by carlio** [comment]
This has been resolved and prospector on Landscape now finds `pylintrc` files

**Comment by syabro** [comment]
Thanks again!
