### ISSUE TITLE
stuck in 'connecting hooks'

### ISSUE THREAD

**Issue by calmrat** [landscapeio/landscape-issues#139]
Hi,  I recently joined landscape.io and added my first repo; it's a repo I'm a collaborator on though, rather than owner of, in case that makes a difference.

Adding the repo wasn't an issue. But something is stuck...

https://landscape.io/repository/144913/status
    Repository information for psss / status-report is being imported.

just stays here ^^^ icon bouncing over and over. Stuck for 4 hours now or more.

Though... just in the past hour I did get an email linking me to for a run one commit... 
https://landscape.io/github/psss/status-report/7

However, I can only get to that page via the direct link, since otherwise I'm brought to the above status page which is stuck somehow.

Any thoughts?

**Comment by calmrat** [comment]
![image](https://cloud.githubusercontent.com/assets/3764092/7300975/e884fd1c-e9df-11e4-8ca2-151d040ecfb7.png)

![image](https://cloud.githubusercontent.com/assets/3764092/7300981/f32c9662-e9df-11e4-992d-df7513a06893.png)

^^^ Just keeps looping the 'connecting hooks' icon

**Comment by carlio** [comment]
This seems to be fixed now (assuming [psss/did](https://landscape.io/github/psss/did) is the correct repo now)
