### ISSUE TITLE
unused variables warning ignore 'unused_' prefix

### ISSUE THREAD

**Issue by pirat89** [landscapeio/landscape-issues#140]
Hi, what is recommended name of variables which we don't want use but we want keep them inside code? I don't want use name **_** and **unused_**' prefix is (or was) accepted by pylint.

Can be this taken into account during testing or is there else recommended style for code?

**Comment by carlio** [comment]
Hi @pirat89 - Landscape uses pylint under the hood so defaults in pylint should still be available. I'll check to see but (theoretically) Landscape should not be changing pylint defaults, perhaps the defaults changed. 

Either way, it seems like a nice feature to add or at least document, as a lot of false positives are to do with unused variables or arguments.

You can also suppress the warning by adding a comment to the line or above it like so:

```
my_var = 1  # pylint: disable=unused-variable
```

**Comment by pirat89** [comment]
Yes, you are right. Sorry that I didn't send additional info earlier, it seems that pylint really dosn't support _unused__ prefix anymore as default for longer time (and it's possible that pylint which I used years ago didn't have default settings on server) :-( My fault that I didn't check actual version before reporting of this issue.

Now it's accepted **dummy_** prefix by default in pylint (and of course, variable name **_** too, but I am not fan of this name inside larger projects), which is acceptable for me. I will try it on landscape, but I expect that it will be ok according to info which you write above. Thanks for response. Some document could be helpful probably for others too in future.

**Comment by pirat89** [comment]
So **dummy_** prefix works. Probably this can be closed
