### ISSUE TITLE
Just recieved a Deterioration email for a 15 day old commit?

### ISSUE THREAD

**Issue by d0ugal** [landscapeio/landscape-issues#142]
Not sure why it happened, but seems wrong. What other details can I provided? This is for the repo mkdocs/mkdocs.

**Comment by carlio** [comment]
Hi @d0ugal , I am currently on a train but had a brainwave about what may be causing it. I'll investigate when I get back later. What is the check number you got the notification for?

**Comment by d0ugal** [comment]
https://landscape.io/diff/139297

Think that is what you need?

**Comment by d0ugal** [comment]
Sorry, ignore that last comment. I was confusing myself. This is the email. So check number 36?

![2015-04-26 21 43 05](https://cloud.githubusercontent.com/assets/48211/7339191/a78609ca-ec5d-11e4-8973-ba8781f23f5e.png)

**Comment by d0ugal** [comment]
Interestingly I got the email again once more on the following day at the same time. Not had it again since tho'

**Comment by shakna-israel** [comment]
Being hit by this, I just got four or five emails for tests that are over a month old.

Been emailed about [35](https://landscape.io/github/shakna-israel/docbuilder/35), [36](https://landscape.io/github/shakna-israel/docbuilder/36) and [37](https://landscape.io/github/shakna-israel/docbuilder/37), when the current latest is [143](https://landscape.io/github/shakna-israel/docbuilder/143).

**Comment by shakna-israel** [comment]
I'm still getting emails about old commits. @carlio?

**Comment by carlio** [comment]
@shakna-israel I have no idea what's causing this - I can't track down anything in the code that would be double-sending emails. I'm starting to wonder if it's the mail sending service retrying rather than Landscape. Have you received any recently?

**Comment by shakna-israel** [comment]
@carlio - I was seeing them, about three a day, up until I committed something new to the `master` branch, after that everything went back to normal.

**Comment by ids1024** [comment]
I've seen this too.

**Comment by carlio** [comment]
I'm going to close this as it's now a year old and no new complaints, and since then I've changed email providers and rewritten the email worker code, so I think (hope!) it's fixed :pray:
