### ISSUE TITLE
Better handling of issue links

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/landscape-issues#143]
When using an issue link of the form `<owner>/<repo>#issue` with `owner`, `repo`, and `issue` subbed out for the user or group, repository name, and issue number respectively, landscape does not seem to parse this correctly and only parses the issue number instead to provide a link. This is notable in commit messages.

**Comment by carlio** [comment]
This works now :)

**Comment by jakirkham** [comment]
Thanks.
