### ISSUE TITLE
Python decorator support / click support

### ISSUE THREAD

**Issue by s-celles** [landscapeio/landscape-issues#144]
Hello,

I use click http://click.pocoo.org/ which is a very convenient Python library for CLI parser.
Unfortunately Landscape doesn't seems to like it see for example

https://landscape.io/github/scls19fr/pycondor/17/modules/pycondor/excel2task.py

```
if __name__ == '__main__':
    main()
No value for argument 'outdir' in function call
No value for argument 'output' in function call
No value for argument 'xls_filename' in function call
```

main function was defined like this

```
@click.command()
@click.argument('xls_filename')
@click.option('--output', default='kml', help="Output type in %s" % supported_output_formats)
@click.option('--outdir', default='', help="Output directory - default is 'script_directory\out'")
def main(xls_filename, output, outdir):
    pass
```

Landscape shouldn't complain about this. It will be nice.

Kind regards

**Comment by evilaliv3** [comment]
@carlio i verify this issue also: https://landscape.io/github/globaleaks/GlobaLeaks/793/modules/backend/globaleaks/handlers/collection.py#L119

it's strange as from pylint should deals with decorators without issues and is able to find the real number of arguments, while here it seems it is failing on that:

@carlio is it possible that you are using still pylint 1.2?
can you make a trial with 1.4?

https://stackoverflow.com/questions/24130248/how-do-i-hide-pylint-1-2-1-error-output-when-using-django

**Comment by cbetti** [comment]
Confirmed pylint 1.4.4 still produces this error when parameters would be provided by click. Seems to me that pylint is doing its job correctly, but that the "if **name** == '**main**'" syntax is just a bad pattern for invoking a program.
