### ISSUE TITLE
Can't see any private github repos

### ISSUE THREAD

**Issue by davidthewatson** [landscapeio/landscape-issues#145]
I signed up using github, but I can't see any private repos. Are private repos supported and working?

**Comment by carlio** [comment]
@davidthewatson Yes, they should be. Are the private repositories on your account or another GitHub organisation? I can see some private repositories for an org you belong to, so has the issue maybe fixed itself?

**Comment by davidthewatson** [comment]
Yes, I can now use the private repo, so I'm past that problem. Thanks!

But now the interface says, Synchronising with GitHub:
×Synchronisation complete

and "Setting Up..."

It's been frozen like that for a half hour. Should I try something else or
does it normally take this long setting up?

David Watson
http://davidwatson.org/

**Comment by carlio** [comment]
Which repository is this for? I see a private repo which has been successfully imported - are you still having the problem? It should normally take a few seconds so if it actually took an hour, that's not good! On the other hand, perhaps if you refresh the page? It could be a problem with the AJAXy status updating thingy.
