### ISSUE TITLE
Synchronization stopped 15 hours ago

### ISSUE THREAD

**Issue by pasztorpisti** [landscapeio/landscape-issues#146]
My repo has not been synced for 15 hours: https://landscape.io/github/pasztorpisti/json-cfg
On the dashboard I've pressed the "Sync with Github Now" button but that hasn't solved the problem. There is also a status indicator label with "Synchronising with GitHub: Queued" text.

**Comment by pasztorpisti** [comment]
It seems to work again. The reason for the delay may be something else than an actual bug but in that case the user interface should be a bit less confusing: People will expect immediate action from a button like "Sync with Github Now". :-)

**Comment by carlio** [comment]
@pasztorpisti Thanks for the bug report - the rabbitmq server died yesterday which is why the sync didn't work immediately like it is supposed to. Sorry about that!

**Comment by pasztorpisti** [comment]
@carlio np, fortunately it wasn't at all urgent for me. After reading another 500 error report in another issue I suspected that my case was just the prologue for that so I've closed this one. :-D
