### ISSUE TITLE
500 error on top level https://landscape.io

### ISSUE THREAD

**Issue by grooverdan** [landscapeio/landscape-issues#147]
wget -S https://landscape.io/ -O /dev/null
--2015-05-02 16:31:01--  https://landscape.io/
Resolving landscape.io (landscape.io)... 45.56.74.79
Connecting to landscape.io (landscape.io)|45.56.74.79|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 500 INTERNAL SERVER ERROR
  Server: nginx
  Date: Sat, 02 May 2015 06:31:04 GMT
  Content-Type: text/html
  Transfer-Encoding: chunked
  Connection: keep-alive
  x-xss-protection: 1; mode=block
  x-content-type-options: nosniff
  strict-transport-security: max-age=31536000
  Vary: Cookie
  x-frame-options: DENY
  Set-Cookie: t=a49475a09b2d4fb3a095c83a6f8def7f; Path=/
2015-05-02 16:31:05 ERROR 500: INTERNAL SERVER ERROR.

**Comment by carlio** [comment]
Fixed now. This is what I get for trying to take a holiday!
