### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by ugocupcic** [landscapeio/landscape-issues#149]
Hi,

I'm getting this `Server Error(500)` from almost all pages except the dashboard. 

For example: 
https://landscape.io/github/shadow-robot/sr-teleop/6/messages/error
https://landscape.io/repository/144978/stop

etc...

When looking at the closed issues, I saw this [issue](https://github.com/landscapeio/landscape-issues/issues/52) and checked that I don't have any file > 1Mb.

Cheers,

Ugo

**Comment by carlio** [comment]
Hi @ugocupcic - this is fixed now, sorry about that. The web server ran out of disk space because it wasn't cleaning up logs properly.

**Comment by ugocupcic** [comment]
Awesome thanks for the quick reply :+1:

**Comment by geeknam** [comment]
Getting 500s again.

**Comment by jantman** [comment]
@carlio I'm seeing them again today...

**Comment by skudriashev** [comment]
@carlio it still gives an error https://landscape.io/github/apache/incubator-airflow/pulls/2511. Anybody working on this?
