### ISSUE TITLE
Potential erroneous "Use of super on an old style class" message.

### ISSUE THREAD

**Issue by thomasmansencal** [landscapeio/landscape-issues#151]
On the first entry of this page: https://landscape.io/github/colour-science/colour/477/messages/error

We get a `Use of super on an old style class` message which if I'm not mistaken is erroneous:

``` python
class SplineInterpolator(interp1d):
    super(SplineInterpolator, self).__init__(
                kind='cubic', *args, **kwargs)
```

`SplineInterpolator` inherits from `interp1d` which itself inherits from `_Interpolator1D` inheriting from `object` which is not an old style class.

**Comment by gtback** [comment]
I've noticed this as well. It seems to occur when the class inherited from is in another library (where presumably it can't tell whether it's a new-style or old-style class). I ran across this when I pulled a base class (`Entity`) into another library (which Landscape now doesn't seem to inspect to realize it's a new-style class). 

https://landscape.io/github/CybOXProject/python-cybox/95/messages/error

I'm not sure if this is a landscape issue or an underlying PyLint/Prospector issue.

**Comment by anentropic** [comment]
Same issue here:
https://landscape.io/github/anentropic/django-conditional-aggregates/12/messages/error

If you go and look at the relevant class in Django framework it inherits from `object`, which means it's a new-style class after all

I don't have Django in my `install_requires` in `setup.py` as I figure that's an obvious prerequisite that users will want to manage the installation of by their own means... but would that help landscape to lookup the dependency?

**Comment by syenchuk** [comment]
Same issue here:
https://landscape.io/github/alexpirine/shelf-cms/56/modules/shelf/admin/widget.py
