### ISSUE TITLE
Stuck for days in "Scheduling first check"

### ISSUE THREAD

**Issue by themattrix** [landscapeio/landscape-issues#153]
Landscape URL: https://landscape.io/repository/153677/status
GitHub URL: https://github.com/themattrix/python-pystrap

I've actually had this happen two times now. The [previous project](https://landscape.io/github/themattrix/python-abduct) got unstuck after a few days.

Maybe it's a coincidence, but the only two times it's gotten stuck were when I added an empty (brand new, no history) repo. Perhaps the worker crashed or is waiting for input?

**Comment by themattrix** [comment]
It's been several months and it's still stuck. Anything I can do to fix this?

**Comment by carlio** [comment]
@themattrix finally managed to get the site working properly, sorry about that.
