### ISSUE TITLE
GitHub PR Integration

### ISSUE THREAD

**Issue by cancan101** [landscapeio/landscape-issues#158]
Integrate into GH as a "check" rather than posting a comment on the PR.
![image](https://cloud.githubusercontent.com/assets/51059/7888611/bf360b06-0607-11e5-8ba6-4488961ba4b6.png)

**Comment by Dunedan** [comment]
:+1:

**Comment by geeknam** [comment]
:+1:

**Comment by jhamman** [comment]
:+1:

**Comment by carlio** [comment]
Just released this, from now on it will use the Status API. Comments are now disabled, although you can re-enable them if you like (useful if you want to keep track of changes throughout a PR, as the status is only the "most recent" commit). Let me know if you notice any issues or if it is not updating or anything, cheers!

**Comment by jhamman** [comment]
Thanks @carlio!  This is a great addition.
