### ISSUE TITLE
Completely unrelated file being blamed for "Cyclic import" pylint warning

### ISSUE THREAD

**Issue by edmorley** [landscapeio/landscape-issues#159]
A file is being blamed for cyclic imports, when it doesn't import any of the modules listed?

ie:
https://landscape.io/github/mozilla/treeherder/1633/modules/deployment/update/update.py#L1

"Cyclic import (treeherder.etl.perf_data_adapters -> treeherder.model.tasks -> treeherder.model.derived.jobs -> treeherder.model.derived.artifacts)"

When (a) none of those modules are imported by update.py, and (b) update.py isn't even listed in the cycle.

I can't reproduce this locally with Pylint - is this just a rendering issue with landscape.io showing where the issues were found?

**Comment by edmorley** [comment]
I've since added that file to .landscape.yaml ignore-paths, and now those warnings have moved to a different, but still unrelated file:
https://landscape.io/github/mozilla/treeherder/1635/modules/puppet/files/treeherder/local.vagrant.py#L1

**Comment by spaceone** [comment]
I have the same issue on an empty file: https://landscape.io/github/spaceone/httoop/17/modules/httoop/cache/__init__.py#L1

**Comment by psav** [comment]
Same issue reported here too https://landscape.io/github/RedHatQE/cfme_tests/33/modules/sprout/manage.py#L1

**Comment by stefano-maggiolo** [comment]
Another example: https://landscape.io/github/stefano-maggiolo/cms/126/modules/cmscommon/eventsource.py

Is this issue being looked into?

**Comment by mistercrunch** [comment]
+1

**Comment by zebpalmer** [comment]
fwiw, I found this issue thread searching for the same problem that I'm seeing in Wing (not using landscape on this). It appears this bug is in pylint itself.  

see http://stackoverflow.com/questions/30656388/pylint-reporting-cyclic-import-on-file-without-imports for possible explanation.

**Comment by carlio** [comment]
This has been a bugbear for a while so I'll close this as duplicate of https://github.com/landscapeio/landscape-issues/issues/214 to keep it all in one place.
