### ISSUE TITLE
Pull request improvements

### ISSUE THREAD

**Issue by lukeyeager** [landscapeio/landscape-issues#160]
> Pull request support is currently experimental. If you notice any problems please report them to the issue tracker.

I'm trying to merge [this branch](https://github.com/lukeyeager/DIGITS/tree/json-routes) ([Landscape](https://landscape.io/github/lukeyeager/DIGITS/json-routes)) into [this branch](https://github.com/NVIDIA/DIGITS/tree/master) ([Landscape](https://landscape.io/github/NVIDIA/DIGITS/master)) using [this pull request](https://github.com/NVIDIA/DIGITS/pull/136), but I don't see anything triggered [here](https://landscape.io/github/NVIDIA/DIGITS). Am I missing something?

**Comment by lukeyeager** [comment]
Oh wait, now it commented on my pull request. Two suggestions:
1. Do "checks" rather than "comments" - #158.
2. Show me that Landscape is working on pull requests [like Travis does](https://travis-ci.org/lukeyeager/travis-python-testing/pull_requests).

Thanks for the cool plugin!

**Comment by jhamman** [comment]
:+1:

**Comment by carlio** [comment]
Just released this, from now on it will use the Status API. Comments are now disabled, although you can re-enable them if you like (useful if you want to keep track of changes throughout a PR, as the status is only the "most recent" commit). Let me know if you notice any issues or if it is not updating or anything, cheers!
