### ISSUE TITLE
Comparison not possible

### ISSUE THREAD

**Issue by spaceone** [landscapeio/landscape-issues#163]
I often force-push fixups. I receive "Comparison not possible".
Is it possible to compare with the commit/build before then?

**Comment by carlio** [comment]
@spaceone What would you like to compare to in that case? Force-pushing does cause complications as the 'previous' check no longer exists, but it could compare to, eg, `master` by default or something?

**Comment by spaceone** [comment]
You can compare to the last existing "build"/"test"/"job" (or however you call it).
