### ISSUE TITLE
Feature Request: "rank Committers by code quality improvement"

### ISSUE THREAD

**Issue by ahnitz** [landscapeio/landscape-issues#164]
For teams it would be very nice to see a page that gives some attribution to who improves the code quality (or introduces new issues).

**Comment by carlio** [comment]
Apologies but I won't implement this as I completely disagree with the premise behind it. I was trying to find the Joel Spolsky article about this but have failed, however the general point is: if you try to rank developers, they'll work towards the ranking not the company goals. I'd hate to create a feature that leads to finger pointing and changes developer incentives.

See also https://en.wikipedia.org/?title=Goodhart%27s_law and http://dilbert.com/strip/1995-11-13

**Comment by ahnitz** [comment]
No apology necessary. Thanks for the explanation.
