### ISSUE TITLE
Radio Buttons not Rendering in Chrome

### ISSUE THREAD

**Issue by cancan101** [landscapeio/landscape-issues#166]
![image](https://cloud.githubusercontent.com/assets/51059/8449324/896e42e4-1f9e-11e5-8306-62c23993ae53.png)

**Comment by carlio** [comment]
I think this is fixed now. Could you please check? I'm unable to reproduce but several people have reported it so it'd be really helpful if you could let me know! @cancan101

**Comment by cancan101** [comment]
This appears to be fixed.
