### ISSUE TITLE
500 Error upon Github login

### ISSUE THREAD

**Issue by ckingdev** [landscapeio/landscape-issues#171]
Clicking any of the "Sign in / Log in with Github" links on the homepage is resulting in an unstyled "Server Error (500)" page with no details. Clearing cookies + cache and retrying reproduced the error page.

**Comment by jantman** [comment]
I'm getting this issue as well. I first saw it about 3 hours ago, and it's still occurring for me. Also, as far as I can tell, Landscape isn't running (automatically on push) for any of my GitHub branches either.

**Comment by carlio** [comment]
Login should be fixed now. @jantman I'm not 100% sure about the checks but GitHub seems to have blocked all of the worker machines from the API right now which is a bit of a problem...

**Comment by jantman** [comment]
Ok. Yeah, login confirmed fixed. And yes, as far as I can tell, builds aren't working.

**Comment by jantman** [comment]
@carlio any update on this?

**Comment by carlio** [comment]
@jantman Yes, they should be working again now. Which repository(s)?

**Comment by carlio** [comment]
@jantman No scratch that, the worker servers are down. I'm working on it.

**Comment by jantman** [comment]
Ok, cool.

I'm not sure how real-time this is, but I confirmed that it wasn't just me by looking at the list of recent builds on https://landscape.io/ and confirming that they're all from early AM on July 14th.

**Comment by carlio** [comment]
@jantman Everything is back up now, but there's a big backlog of checks to get through, may take several hours to clear.
