### ISSUE TITLE
the first check never ends

### ISSUE THREAD

**Issue by luzfcb** [landscapeio/landscape-issues#172]
I tried deleting the build by clicking the red `'x'` on the Dashboard, tried to create the `.landscape.yml` file and then tried to set `autodetect: no`,  but the first check never ends

https://landscape.io/github/luzfcb/django_documentos

**Comment by Thor77** [comment]
Yeah, i have the same problem.

**Comment by pennyarcade** [comment]
My latest check number #39 has been running for over 12 hours now...
The shippable build running many of the same tools is done in about 5 to 10 minutes.
I guess there is something seriously wrong.
https://landscape.io/github/pennyarcade/py_pov/39

**Comment by carlio** [comment]
Yes the worker server was dead for a while (could not access GitHub). It's up now and these should all complete eventually, there's a backlog that is being worked through

**Comment by carlio** [comment]
These repos all seem to be working again now, sorry about that - please let me know if not!

**Comment by Thor77** [comment]
everything works fine now (at least for me) :+1:
