### ISSUE TITLE
Please integrate with GitLab.com

### ISSUE THREAD

**Issue by thozza** [landscapeio/landscape-issues#173]
Hi.

Since Gitlab started to provide projects hosting of their own, It would be really nice to be able to add repositories also from gitlab.com, not only from github. The same for login. There seems to be no other login method besides github on landscape.io at the moment

**Comment by thozza** [comment]
@carlio do you have any update on this?

**Comment by IceflowRE** [comment]
Something new here?

**Comment by Freso** [comment]
Guess it’s my turn for the annual request for an update. :)

**Comment by Freso** [comment]
Was this closed because it’s been implemented, or because it’s been discarded and won’t be implemented?

**Comment by carlio** [comment]
Landscape basically died and I'm trying to rebuild it so to get a fresh start I mass-closed the issues. I will try to do this eventually though but it rather depends on the rewrite.
