### ISSUE TITLE
PermissionError wrongly reported as error (undefined variable)

### ISSUE THREAD

**Issue by tomschr** [landscapeio/landscape-issues#177]
Consider the following code:

``` python
try:
  # something
except PermissionError:
  # something
```

Landscape reports the code above with this error:

```
pylint: undefined variable (E0602 )
```

However, this is wrong: Since version 3.3,  the Python developers reworked the OS exception hierarchy:

https://docs.python.org/3/whatsnew/3.3.html#pep-3151

Probably other errors are also affected.

**Comment by mschnitzer** [comment]
confirmed

**Comment by ids1024** [comment]
Landscape is currently python 2 only: #32
