### ISSUE TITLE
Entire site appears to be down

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/landscape-issues#179]
<img width="1440" alt="screen shot 2015-08-20 at 10 15 04" src="https://cloud.githubusercontent.com/assets/3019665/9385447/7967153a-4724-11e5-93d9-56246ac8c507.png">

**Comment by carlio** [comment]
I think it's safe to say the migration to heroku has been an unmitigated disaster

**Comment by teleyinex** [comment]
It's down from here too :-) Sorry to hear that.

**Comment by bittner** [comment]
So, when will you migrate back onto the servers of your living room?  :see_no_evil:

I need Landscape up again before the end of 2017.  :grimacing:

**Comment by carlio** [comment]
I'm planning a new migration ASAP back to regular hardware. It's probably easier to fix issues I used to know about than re-investigate a whole new platform :(

**Comment by jakirkham** [comment]
If you are really wishing to migrate, eventually, maybe you could expose the new heroku-based version on something like beta.landscape.io that way you can continue to work on it and maybe we can give you some feedback. :)

**Comment by jakirkham** [comment]
Looks like the old site is back. Closing...

**Comment by jakirkham** [comment]
It's back.

**Comment by jakirkham** [comment]
Ok, I spoke too soon. Sorry...

**Comment by jakirkham** [comment]
Ok, this appears to be somewhat intermittent, but it does seem to be an issue again.

**Comment by lukeyeager** [comment]
Two weeks now and the site is still down? Should I start looking for other options?

**Comment by bittner** [comment]
@lukeyeager Please. Don't be rude. Landscape is an awesome service. It was up for a week or so, now there are some other issues. What's the problem? How much do you pay? Donate, so he can have better service!

**Comment by lukeyeager** [comment]
@bittner, good point. I apologize.

**Comment by jakirkham** [comment]
Alright, the dashboard appears to load fine. However, the repos themselves are not loading reliably (at least mine aren't).

**Comment by jakirkham** [comment]
Alright, we are back to the entire site just not loading.

**Comment by carlio** [comment]
Ok, the downtime should be gone or at least minimal now. I'll leave this open to see if things have really improved. Really sorry everyone.

**Comment by jakirkham** [comment]
It does appear to be much more responsive. Is there a way for me to terminate/restart a scan that occurred during the outage?

**Comment by carlio** [comment]
@jakirkham If it failed, there's a "try again" button. Otherwise if you want a specific commit hash or branch let me know and I'll kick it off manually.

**Comment by jakirkham** [comment]
It just appears to be waiting and not doing anything. Honestly, I can delete and readd the repo if that wil work as this was the very first scan.

**Comment by carlio** [comment]
@jakirkham what repository / check number?

**Comment by jakirkham** [comment]
This one ( https://landscape.io/github/DudLab/mouse_record ).

**Comment by carlio** [comment]
@jakirkham here you go: https://landscape.io/github/DudLab/mouse_record/2 (I had to cancel the first one)

**Comment by jakirkham** [comment]
Ah, perfect. Thanks @carlio.

**Comment by jakirkham** [comment]
Yeah, this seems to be completely down again. I tried several times yesterday and today.

**Comment by jakirkham** [comment]
Seems to be back.

**Comment by mdsitton** [comment]
I've had loading issues all day, so this is def not fixed...

**Comment by jhamman** [comment]
was working fine this morning, now seems to be hanging all over the place.  

@carlio - This service is great, I'm just wondering if you can give your users some idea of a time frame for when we may see things stabilize?

**Comment by jakirkham** [comment]
I think this is just down when it is getting hammered frequently as I notice there are periods with this problem and periods without. Are the badges cached?

**Comment by dlobue** [comment]
I'm getting this issue as well. Every other page load seems to fail.
I'm currently trying to demo this for work, and this is not making a great first impression...

**Comment by mdsitton** [comment]
Well i've been in irc channel for a while, and, he should be able to work full time on landscape for a couple of months. So hopefully this gets solved for good soon!

**Comment by thedrow** [comment]
If you need help with deployment let me know. I might be able to consult you on how to deploy this correctly.

**Comment by carlio** [comment]
Finally fixed :)  back to proper hardware instead of herkou.
