### ISSUE TITLE
Failure reason: Prospector execution failed

### ISSUE THREAD

**Issue by adesnos** [landscapeio/landscape-issues#180]
Hi I got this error when I tried to import:
https://landscape.io/github/androguard/androguard/

**Comment by carlio** [comment]
Hi @adesnos , it seems like something in your code is making Pylint fail. I'll investigate and see what I can find out.

**Comment by adesnos** [comment]
ok cool thank you

**Comment by adesnos** [comment]
Have you find something ?

**Comment by revesansparole** [comment]
I seem to have the same type of issue. landscape working fine without .landscape.yml file.
Tried to add empty .landscape.yml file -> fail
tried to add the one given in documentation -> fail
tried to edit it as per current file -> fail
https://landscape.io/github/revesansparole/ltpkgbuilder

Any help on minimalist .landscape.yml that I need to write to start testing?

**Comment by carlio** [comment]
I'm doing some spring-cleaning of really old issues, and pylint has moved on to version 1.5.6 so perhaps this is now fixed, not sure.
