### ISSUE TITLE
Dashboard shows Synchronising with GitHub: Queued

### ISSUE THREAD

**Issue by mtimm** [landscapeio/landscape-issues#181]
I have several public repos added from a github organization.  They don't seem to be sync'ing properly from github.

The dashboard shows:

```
Synchronising with GitHub: Queued"
```

It also shows:

```
Your list of repositories is automatically synchronised with GitHub every few hours.
Your account was last synchronised 8 hours ago
```

If I try to manually sync, 8 hours ago it would seem to suggest a sync was happening but nothing would get updated.  Now it seems stuck and not even sync'ing manually.

Here is list of the repositories:

https://landscape.io/github/datacenter/AryaLogger
https://landscape.io/github/datacenter/SimpleAciUiLogServer
https://landscape.io/github/datacenter/acitoolkit
https://landscape.io/github/datacenter/cobra

I also added a repo and it shows as being stuck adding the webhook - https://landscape.io/repository/200288/status

Thanks!

**Comment by nanorepublica** [comment]
:+1: experiencing the same here for new repos that I am trying to add

**Comment by carlio** [comment]
Looks like the user syncing queue got gummed up. I just re-started the syncing jobs, hopefully that'll fix your users. I'll now check the repositories.

**Comment by carlio** [comment]
@nanorepublica which repositories did you try to add?

@mtimm have you removed access for Landscape since you created this post? It can't sync repo data with your organisation

**Comment by nanorepublica** [comment]
@carlio, they were 2 repos from the founders4schools organisation, they have now both successfully been processed. Thanks for the quick response :smile:

**Comment by mtimm** [comment]
@carlio I have not revoked access for Landscape.io and the organization has no restrictions either.  Should I try revoking it and setting it back up?

**Comment by mtimm** [comment]
Things seem to be working as expected now.  Thanks.
