### ISSUE TITLE
BUG: Unable to turn off comments for pull requests on organizations

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/landscape-issues#182]
It seems we don't have control over whether comments will be posted for pull requests against organizations that we administer. Or am I missing this somewhere? If not, is it possible for this feature to be added?

**Comment by jakirkham** [comment]
Nevermind. Totally missed this somehow. Sorry for the noise.

**Comment by jakirkham** [comment]
Well, though there is the option, it appears that I am not allowed to change this setting. I get this error "is not a member of DudLab". It looks like it meant to say my username, but it didn't. I can't tell if this is related to the bug or a separate issue.

**Comment by arikfr** [comment]
The same just happened to me. I wanted to turn off the comments, as they were always coming in several hours _after_ I merge the pull requests...

I will appreciate if you could either fix this, or manually disable comments for EverythingMe/redash repo. Thanks.

**Comment by carlio** [comment]
@arikfr I have manually disabled the comments and will look into why this is happening now.

**Comment by arikfr** [comment]
:+1:

**Comment by carlio** [comment]
@jakirkham @arikfr I found the issue, a rather nasty thing to do with weakened ETag headers...

Let me know if it isn't fixed, but I think it should be!

**Comment by jakirkham** [comment]
Thanks. Will keep an eye out for this one.
