### ISSUE TITLE
Setting up new repository hangs

### ISSUE THREAD

**Issue by jhamman** [landscapeio/landscape-issues#183]
I'm trying to setup landscape on a new repository (https://github.com/xray/xray).

After adding the repository on Landscape, the setup is hanging here: https://landscape.io/repository/189500/status

**Comment by mtimm** [comment]
+1

I have the same issue, reported in #181

**Comment by jhamman** [comment]
I don't think it is the same issue as #181.  I'm stuck on `Connecting Hooks`.  

`GitHub Synchronisation` seems to be working fine.

**Comment by mtimm** [comment]
Sorry for the confusion, I meant I am seeing the same issue with a newly added repo.  I did mention this in #181.

> I also added a repo and it shows as being stuck adding the webhook - 
> https://landscape.io/repository/200288/status

**Comment by carlio** [comment]
@jhamman I have un-gummed the queue, and the `xray` repo is now working. 

@mtimm the wiper repository is now also unstuck.

Sorry both; these infrastructure issues are going away this weekend I promise!

**Comment by mtimm** [comment]
@carlio thanks I went to the dashboard and wiper wasn't shown.  So I then went to add repository and clicked on the organization it is under and the wiper repo was not shown as already being checked.  I have tried adding it again and so far it seems stuck at the webooks stage again.  I'll leave it there and wait for the weekend.

**Comment by carlio** [comment]
@mtimm ok, I think this is a different issue, I think for whatever reason Landscape doesn't see you as being a member of that organisation. I'll look into it.

**Comment by Zitrax** [comment]
I added a [repository](https://landscape.io/repository/209114/status) yesterday and it's still stuck at "Checking out".

**Comment by carlio** [comment]
@Zitrax your repo is unstuck now. It'll take a little while to get checked as there's a bit of a backlog but it's in the queue now!

**Comment by amorison** [comment]
I'm afraid I also have the same problem. I added [this repo](https://landscape.io/repository/231185/status) but it's still stuck at "Connecting hooks"...

**Comment by amorison** [comment]
Never mind, it seems to be OK now.

**Comment by mtimm** [comment]
Yeah the issue I was seeing with an org repo getting stuck at the adding we hooks stage seems to have gone away or has been addressed in someway.  I added the repo again landscape was able to do its thing just fine.

**Comment by freetheinterns** [comment]
I am also seeing the issue mentioned above. I was able to add a repo, but Landscape.io gets stuck on the 'connecting hooks' step of the setup. https://landscape.io/repository/395697/status

**Comment by allthatilk** [comment]
I'm having this 'connecting hooks' problem too. Was there a solve for this?

**Comment by akhilputhiry** [comment]
@carlio My repository is also stuck https://landscape.io/repository/824753/status. Please help

Edit: I tried deleting the previous one and tried creating new. Still it is stuck :(
