### ISSUE TITLE
BUG: Transfered repo not handled properly

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/landscape-issues#185]
It appears that a repo that is transferred will not show up as a new repo on landscape. Further, if that repo is forked back to its original location, this further confuses landscape. It seemed to think there were two copies under the old account. One being checked and the other not. After some syncing and attempted adding the fork was fixed, but the transferred repo never appeared.

**Comment by carlio** [comment]
@jakirkham This is likely due to the recent woes which are fixed now. Which repository? (before and after names would be please!). I'll find out if this is a bug in syncing state or just because the sync job didn't run in the first place

**Comment by jakirkham** [comment]
Good call. You're right. It was synced over very recently. This appears to fix it. FYI, it was `nanshe`, which I moved from my user to `nanshe-org` and then I forked back to my user.

**Comment by jakirkham** [comment]
So, I am seeing check failures on both of these repos. Is it possible that something is still not behaving correctly with this transfer?
