### ISSUE TITLE
No way to delete a repository from the list

### ISSUE THREAD

**Issue by edmorley** [landscapeio/landscape-issues#186]
I'd like to delete https://landscape.io/github/mozilla/treeherder from the list of repositories shown when logged in, but I can't.

I'm presuming this feature doesn't exist at the moment?

**Comment by carlio** [comment]
There's a little red cross on the top right which (enigmatically) should do that, although it stops checking entirely rather than hiding. Do you want hiding or stop checking?

**Comment by edmorley** [comment]
I can't see a red cross on https://landscape.io/github/mozilla/treeherder at all ?
I'd like to stop checking entirely please.
Thanks :-)

**Comment by carlio** [comment]
@edmorley Oh sorry. It's only on the dashboard summary. That's an oversight I'll fix.

**Comment by peterjc** [comment]
I found the little red cross on the dashboard, but is that still the only route to stop checking a repository?

I was expecting perhaps the "Add repository" screen could be expanded to add/remove?

**Comment by carlio** [comment]
Individual repositories now have a red cross on their page as well as the dashboard option being more obvious. I'll look into adding it to the 'add repository' page too as I plan to go through the UI and make a bunch of small improvements.
