### ISSUE TITLE
Notification page throws error 500

### ISSUE THREAD

**Issue by renefritze** [landscapeio/landscape-issues#187]
Clicking on [Email Notifications](https://landscape.io/preferences/notifications) [here](https://landscape.io/preferences/github-access) results in an error 500 page for me.

**Comment by carlio** [comment]
@renemilk do you still have this issue?

**Comment by renefritze** [comment]
This works for me now, after de-authorization and re-authorization.

**Comment by carlio** [comment]
@renemilk great, thanks for testing. I think this was due to being logged into landscape after the token was no longer valid, so GitHub requests failed in the background.
