### ISSUE TITLE
Cannot disable commenting on pull requests

### ISSUE THREAD

**Issue by renefritze** [landscapeio/landscape-issues#188]
I want to select "No" in the first radio box list on https://landscape.io/preferences/repo/github/pymor/pymor/pull-requests
Clicking "Save Preferences" however results in the error "is not a member of pymor" in the second paragraph. The selected value in the combobox is "the default org setting (none set explicitly)".

**Comment by carlio** [comment]
@renemilk Have you de-authorized Landscape since you reported this issue? There isn't a token for your account so I don't know if that's the bug or something else caused it!

**Comment by renefritze** [comment]
Yeah, I did that. Do you want me to try re-authorize and re-check? Same with #187 ?

**Comment by carlio** [comment]
@renemilk yes please!

**Comment by renefritze** [comment]
Still the same

**Comment by carlio** [comment]
Ok, I'll take a look, thanks!

**Comment by carlio** [comment]
@renemilk should be fixed now, turns out the form was submitting an empty string for the username to comment as (rather than not being set which was expected)

**Comment by renefritze** [comment]
Confirmed. Thanks!
