### ISSUE TITLE
Add organization to account *after* creating account

### ISSUE THREAD

**Issue by felixduvallet** [landscapeio/landscape-issues#189]
I initially signed up for landscape.io and did not give access for an organization I admin. After giving landscape a try, I would now like to add this organization to the available repositories on my landscape.io account.

The page: https://landscape.io/preferences/github-access
only asks me to give github access to my private repositories, not public repos of this organization.

I searched in the docs and FAQ and did not find an answer.

How can I add an organization now that I've already created my landscape.io account?

**Comment by thedrow** [comment]
I have this problem as well. I can't use landscape.io on a new organization I created.

**Comment by carlio** [comment]
@felixduvallet @thedrow Do you still have this problem? Organisation membership should sync eventually. Can you also tell me the names of the organisations? Thanks!

**Comment by thedrow** [comment]
Yes I still have that problem.
I'm having problems with the getdrifter organization.

**Comment by carlio** [comment]
It seems like the GitHub API just isn't returning new organisation membership information. I just created a new one and have the same issue. I will send a message to GitHub support.

**Comment by carlio** [comment]
It turns out that newly created organisations now have 3rd-party access disabled by default, so they won't show up even if you log out of landscape and in again. I will add some text to the add-repository page to explain this and what to do.

In the meantime, if you want to add new organsations:
- go here: https://github.com/settings/connections/applications/82ca3a47d218a80f3962  then allow access to landscape
- go to your dashboard here: https://landscape.io/dashboard and click 'Sync with GitHub now'

**Comment by felixduvallet** [comment]
Thanks for the workaround, that worked for me and my organization. (Note
the link wasn't the same URL for me, so you may need a different way to
point users to the right place.)
Felix

**Comment by carlio** [comment]
@felixduvallet thanks for the heads-up, I noticed other services like travis-ci were using some kind of hex-string in their URL. I'll have to find out where that comes from!

**Comment by carlio** [comment]
Corrected link: https://github.com/settings/connections/applications/82ca3a47d218a80f3962

**Comment by felixduvallet** [comment]
This works for me.
Felix

**Comment by thedrow** [comment]
@carlio I already did before I commented on this issue and the organization still doesn't appear after I sync.
