### ISSUE TITLE
Mail user only if commit has notifically improved/degraded quality of codebase

### ISSUE THREAD

**Issue by rafalp** [landscapeio/landscape-issues#19]
First off, thanks for Landscape. Its nice tool that has capabilities for becoming something awesome.

Now, I commit and push to github plenty, and when this happens Landscape basically spams me with emails that tell me "nothing changed".

IMHO mails could be configured to be sent only when notificable change occurs, or periodically, like x days after commit, that would be much appreciated.

Thanks!

**Comment by carlio** [comment]
There are now more fine-grained options for notifications:
- Every check
- Only changes
- Only degredations
- Never

You can change your settings here:  https://landscape.io/account/notifications

(The default was set to 'only changes')

**Comment by rafalp** [comment]
Good man :+1:
