### ISSUE TITLE
Analysis is not being performed since October, 14 (Failure reason: Unknown)

### ISSUE THREAD

**Issue by vasily-v-ryabov** [landscapeio/landscape-issues#192]
Many latest checks were not run due to unknown reason for our open source project.
It was started from [check 40](https://landscape.io/github/pywinauto/pywinauto/40) and continues including recent [check 68](https://landscape.io/github/pywinauto/pywinauto/68). Latest successful check is [39](https://landscape.io/github/pywinauto/pywinauto/39).

```
Check number 68 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.

Failure reason: Unknown

We don't know exactly why this error happened yet
```

**Comment by carlio** [comment]
@vasily-v-ryabov I fixed this and restarted all checks for the recent failures.

**Comment by vasily-v-ryabov** [comment]
@carlio , it seems working perfectly now. Thanks a lot!
