### ISSUE TITLE
No analysis since October; Failure reason: Unknown

### ISSUE THREAD

**Issue by patkan** [landscapeio/landscape-issues#194]
Since October 11th we have the same problem with fau-fablab/FabLabKasse as in #192.
Please let me know if I can provide useful information.

**Comment by carlio** [comment]
@patkan It was the same issue which is now fixed - the newer checks for FabLabKasse are working. I've re-queued the failed ones from the last few weeks.

**Comment by patkan** [comment]
Thank you!
