### ISSUE TITLE
It looks like the health score is incorrect for the update because full re-analysis had produced another percentile

### ISSUE THREAD

**Issue by vasily-v-ryabov** [landscapeio/landscape-issues#198]
Hi again,
After fixing #192 the full re-analysis was performed for [commits before master 72](https://landscape.io/github/pywinauto/pywinauto). That's great.

But starting from master 72 ([2 new commits at November, 8](https://github.com/pywinauto/pywinauto/commits/master) with only 5 lines of code changed and **2 binaries** added) the score of project had been changed to 90% (instead of previous 97%).

Such a big score change looks incorrect because the real source code is almost not changed. Maybe the previous score (97%) is really incorrect. I don't know. It's not clear to me how the health score is calculated. I could not quickly find it in the docs. Any explanation would be useful.

If a binaries size (and a whole repo size) really matters, I'd suggest to exclude binaries size from the ratio formula to be more objective.

Thanks!

**Comment by carlio** [comment]
@vasily-v-ryabov you're right, the binaries size is taken into account but it shouldn't be, only Python files should affect the score. Thanks for the report, I'll look into it!

**Comment by carlio** [comment]
I'll also add something to the docs about how the score is calculated

**Comment by vasily-v-ryabov** [comment]
Are there some news?
