### ISSUE TITLE
Incorrect time zone

### ISSUE THREAD

**Issue by valsaven** [landscapeio/landscape-issues#201]
I've gotten 4 Dec 2015, 7:04 a.m., but right now here is 11am. Can I change it?

**Comment by carlio** [comment]
Can you tell me which timezone on which page? Also which repository? Thanks!

**Comment by valsaven** [comment]
UTC+5
https://landscape.io/github/valsaven/gtn/7
It writes 5:35am instead of 9:35am

**Comment by carlio** [comment]
@valsaven Timezone is now detected based on ip lookup - if it's still not correct, you can also set it manually here: https://landscape.io/preferences/locale :beer:
