### ISSUE TITLE
All Checks Failing since Friday (Possibly Related to Status API Change)

### ISSUE THREAD

**Issue by xwsxethan** [landscapeio/landscape-issues#203]
Ever since Friday (at least I think, I can't easily find history further back), all the branches in my repo have  had the landscape check fail. Here is the detail text:

`Check number 60 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.

Failure reason: Prospector execution failed

The checking tool, prospector, did not complete correctly`

Usually this isn't a problem and seems to work with a subsequent commits/PR. However, all my commits and PRs have started failing. I'm not sure what other details to include here to help address the issue, but feel free to comment or email, and I'd be happy to help debug. Thanks!

**Comment by carlio** [comment]
Hi @xwsxethan , this turned out to be an underlying prospector bug related to pylintrc files. I've fixed it now and re-run the failed checks for your repository (although only the master branch, as the other checks can't be run due to the branch being deleted now). Cheers!

**Comment by xwsxethan** [comment]
I just saw and came back to check. Thanks for the prompt fix, looks better than ever!
