### ISSUE TITLE
Reworked pull requests don't get status updates

### ISSUE THREAD

**Issue by tomato42** [landscapeio/landscape-issues#205]
So it looks like the #202 did not get fixed completely, tomato42/tlslite-ng#68 is still not getting status updates. Note that this is a pull request which was re-based and re-pushed.

**Comment by carlio** [comment]
@tomato42 Figured this out I think - the GitHub repository push hook for Landscape was only sending `push` events for your repository, not the `pull_request` events. This was the old setting which should have been updated but it seems it was not for your repository. I have updated it now, so if you try again you should get status updates.

**Comment by tomato42** [comment]
Unfortunately can't confirm that it's working: https://github.com/tomato42/tlslite-ng/pull/82

**Comment by carlio** [comment]
@tomato42 This this is figured out now. It was failing to start the comparison because it was trying to set the status on kkaarreell's repository instead of the base repository. Future PRs should work, or if you push changes to that one. Sorry, seems like this was 3 different bugs all together!

**Comment by tomato42** [comment]
And indeed it seems to be fixed.

Thank you very much!

**Comment by carlio** [comment]
Joy unconfined :)
