### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by jeda** [landscapeio/landscape-issues#207]
When I did a commit, I saw Landscape didn't receive it. When I set it to test myself, it has been frozen "testing" for days. It's not working for nothing.

**Comment by PradheepShrinivasan** [comment]
i am also facing the same error. Landscape.io seems to be stuck in checking out the git repo

**Comment by jeda** [comment]
@carlio Can you get on this?

**Comment by frol** [comment]
It seems that something went seriously wrong on the Landscape.io backend. I have recently signed up on Landscape and my Github repos sync never finishes.

**Comment by doismellburning** [comment]
@JeDa @PradheepShrinivasan @frol Hi all - I'm a friend of @carlio's. Unfortunately right now he's in hospital recovering from an accident.

It looks like the Landscape service is having a few problems right now. We're all hoping Carl will be up and about soon, at which point he'll be able to do something about it!

Until then, if you could please have patience while he recuperates! Thanks

**Comment by frol** [comment]
@doismellburning Thank you for the notice. I wish @carlio well!
