### ISSUE TITLE
The syncing not work

### ISSUE THREAD

**Issue by rafaelcb21** [landscapeio/landscape-issues#208]
When I click the button to add repositories in the Landscape is trying to sync, but it never ends.
It appears on the screen and does not end the process:

``` console
Please Wait ...
Fetching your repository list from GitHub. This should only take a few seconds.
Current status: queued
```

**Comment by romansalin** [comment]
I have the same problem. Fetching my repository continued for the second day.

**Comment by doismellburning** [comment]
@rafaelcb21 @romansalin Hi all - I'm a friend of @carlio's. Unfortunately he's currently in hospital recovering from an accident.

It looks like the Landscape service is having a few problems right now. We're all hoping Carl will be up and about soon, at which point he'll be able to do something about it!

Until then, if you could please have patience while he recuperates! Thanks

**Comment by jakirkham** [comment]
That's horrible. I hope he is doing ok.

**Comment by LisandroGuerra** [comment]
Same problem here.

**Comment by carlio** [comment]
@rafaelcb21 @romansalin @doismellburning  @jakirkham @LisandroGuerra Hi all, the basic reason for all this can be found [here](https://github.com/landscapeio/landscape-issues/issues/210). I, the Landscape developer, am currently really quite broken by a road accident. This will all eventually be working again, it's just going to take some time. Please keen an eye out, I'll get back to you when I can get into a developing mode again soon.

**Comment by carlio** [comment]
This is quite an old issue now and I've completely revamped the infrastructure since it was reported so I think it should be fixed. However if you are still seeing problems please re-open this issue!
