### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by mfcovington** [landscapeio/landscape-issues#209]
I'm getting a Server Error 500 at https://landscape.io/github/mfcovington/pubmed-lookup/master

**Comment by carlio** [comment]
@mfcovington Hi there, this is on my todo list to fix ASAP. It seemed to get wedged into a funny state recently where it refuses to write to the DB. Unfortunately, I wedged myself into a funny state on a motorbyce recently and that injury and recovery is why it may take some time to get this back up and running. You can read more [here](https://github.com/landscapeio/landscape-issues/issues/210)

**Comment by mfcovington** [comment]
@carlio Ouch! I'm sorry to hear about your accident. Hope you have a full recovery.

**Comment by carlio** [comment]
Landscape is mostly working again now so I will close this! For the record, I'm doing much better now, thanks :)

**Comment by mfcovington** [comment]
@carlio Thanks! Very happy to hear that you are doing well!

**Comment by skudriashev** [comment]
Having this issue: https://landscape.io/github/apache/incubator-airflow/pulls/2520

**Comment by skudriashev** [comment]
@carlio could you please answer this?
