### ISSUE TITLE
Landscape Developer inured and unavailable

### ISSUE THREAD

**Issue by carlio** [landscapeio/landscape-issues#210]
Hi all, I'm @carlio, creator of @landscapeio and things like @prospector. This is a very dear project of mine and I love that so may people use it and have set up their open source projects to be checked automatically every day for new issues.

Unfortunately, I was recently in a severe motorcycle crash. In the mean time Landscape has fallen a little into disuse and needs a bit of tender loving care just to get it back up and running consistently. It's not a huge amount of work and don't worry, I will be doing it and brining everything back as soon as possible.

I will have to beg your forgiveness and patience in the mean time though, I have had a few litres of blood drained from a lung wound, reconstructive surgery on a my back and shoulders, and various other things that I didn't even know existed are now in a mess.

I will be rebuilding this project soon, I just need a few days to recollect my thoughts. Thanks again for your support and interest in this project. It will be back!

Feel free to leave a sarcastic comment or jibes about my terrible driving here too for posterity :+1: I'll set up a special "ha look wat a doofus" blog post afterwards. (By the way I haven't yet withdrawn my threat to show a picture of my reconstructive clavicle surgery. Only you can prevent that travesty with a steady torrent of sarcasm!)

For anyone wondering, the short version is that currently the DB is wedged full, so new checks probably aren't happening. I'll get them all re-queued when I can. For what it's worth, you can still run "Landscape" yourself locally using [prospector](http://prospector.readthedocs.org/) which is kind of a nice command-line version of it. It's not the ideal replacement but you may find it useful.

**Comment by macskay** [comment]
Hey man! Sorry to hear what happened! Looking forward to the fixes, whenever you've got some free time and feeling better. Until then: Get well soon!

**Comment by tofu-rocketry** [comment]
Hope you feel better soon. :+1:  

The problems with Landscape have encouraged me to try some other hosted code review sites, but I still prefer Landscape's way of doing things. :ok_hand:

**Comment by nicodv** [comment]
100% physical health is far more important than 100% code base health.  Take your time, and good luck with your recovery!

**Comment by deejay1** [comment]
Get well soon! We can wait, at least landscape won't be making silly comments about our codebase (they have to be silly, because our code is perfect - just like everyone else's!)

**Comment by dArignac** [comment]
Thanks for getting in touch about the circumstances. Get well soon!

**Comment by haraball** [comment]
@carlio 
![image](https://cloud.githubusercontent.com/assets/25930/12617317/6e0e41e0-c50f-11e5-8466-ececcb92d20c.png)

**Comment by shidarin** [comment]
Get well soon!

**Comment by jeffwidman** [comment]
This should probably be closed based on https://github.com/landscapeio/landscape-issues/issues/209#issuecomment-184622617 

Glad to hear you're doing better!

**Comment by acdha** [comment]
Glad to hear @carlio is feeling better – hard to imagine anyone being happier to close an issue!

**Comment by carlio** [comment]
Thanks all, and @acdha you're right, looking forward to closing this when I can. Hopefully not as "won't fix" :)

**Comment by carlio** [comment]
Well I am extremely glad to report I can now close this issue :)  No more CT-scans for me!  Next steps: figure out how to work on Landscape full time!
