### ISSUE TITLE
Landscape and python 3.5 (await / async keywords)

### ISSUE THREAD

**Issue by Insoleet** [landscapeio/landscape-issues#211]
Hello,

I'm trying to use the latest landscape python3 feature. But it does not look like to work correctly.

https://landscape.io/github/ucoin-io/sakia/464/modules/src/sakia/core/registry/identity.py#L93

As you can see, there is a syntax error present because of the `async` keyword. This keyword is only present since python 3.5. Maybe you need to run pylint with python 3.5 ?

**Comment by carlio** [comment]
@Insoleet yes you're right, currently it's still using 3.4 .  Should be fairly straightforward to update that to 3.5 soon.

**Comment by bagrat** [comment]
Hi @carlio, is this work in progress or any updates?

**Comment by bagrat** [comment]
Here is my problem. More than a week ago I did not have problems with the `async` stuff:

https://landscape.io/github/n9code/calm/34/modules/calm/core.py#L274

Today, it started to show up:

https://landscape.io/github/n9code/calm/36/modules/calm/handler.py#L94

The only difference is that I moved that piece of code to another file.

**Comment by bagrat** [comment]
Moreover, when reverting the code, the `async` passes again.

**Comment by carlio** [comment]
@n9code Good news! I managed to get the containers running Python 3.5.1 so the async syntax errors have gone. Bad news: I also upgraded the pylint version so you have some new bonus errors in https://landscape.io/github/n9code/calm/36/modules/calm/handler.py#L94 ... but at least aysnc is fixed :)

**Comment by bagrat** [comment]
@carlio the more errors landscape catches, the better :) thanks a lot!
