### ISSUE TITLE
Delete old PR comments

### ISSUE THREAD

**Issue by gazpachoking** [landscapeio/landscape-issues#215]
It would be nice if landscape-bot could delete all old status comments on a PR when adding a new one. Some of our PRs get pretty spammy with all the updates, but it is nice to always have the latest status as a comment, as it's more visible to new contributors than the build status.

**Comment by carlio** [comment]
What do you think about adding an option in the preferences for this? A few people have asked in the past for keeping old comments as it gives a "history" of updated PRs, so it's probably something that should be left configurable.

**Comment by gazpachoking** [comment]
An option sounds good, I was almost going to suggest it that way, but I couldn't think of an use for the old ones. If other people like that behavior, making it optional makes sense.
