### ISSUE TITLE
Check completed, but PR Status does not show that

### ISSUE THREAD

**Issue by renefritze** [landscapeio/landscape-issues#217]
We've seen this a couple of times over the last few days. 
Example: [completed check](https://landscape.io/github/pymor/pymor/445) vs [associated PR](https://github.com/pymor/pymor/pull/223)

**Comment by brifordwylie** [comment]
+1 we're seeing the same thing for the dpkt github project.

**Comment by renefritze** [comment]
Seems to have fixed itself
