### ISSUE TITLE
"Prospector execution failed" for pywinauto for a long time

### ISSUE THREAD

**Issue by vasily-v-ryabov** [landscapeio/landscape-issues#219]
Analysis fails for [pywinauto](https://github.com/pywinauto/pywinauto) (branch "UIA").
Landscape shows the following error ([check 90](https://landscape.io/github/pywinauto/pywinauto/90)):

```
Check number 90 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.

Failure reason: Prospector execution failed

The checking tool, prospector, did not complete correctly
```

The latest successful check is 76. Adding forked repo for analysis also fails (prospector seems hang up).

I haven't filed an issue for all this time because Landscape says `we have been notified`, but it looks like nobody knows about these failures.

**Comment by carlio** [comment]
Hi @vasily-v-ryabov , I was looking into this. Seems like one of the worker servers decided to claim all of the jobs, then get completely locked up. I've removed that worker for now so future checks will hopefully get back to normal. Apologies for not reacting that fast, still as a result of #210 but I am getting there!

**Comment by vasily-v-ryabov** [comment]
Now it works. Thanks a lot!
