### ISSUE TITLE
The timeline of Landscape.io gets currupted if GitHub is overloaded

### ISSUE THREAD

**Issue by Paebbels** [landscapeio/landscape-issues#222]
I noticed that GitHub was overloaded:
- files were pushed but not visible on github.com
- Landscape.io didn't got a push notification, but manual checking, checked the latest files from github

Some time later, I got an email from Landscape.io, that a check was finished (an older one).

As you can see in the screenshot, the checks are not in time order and do not correspondent to the commit order.

![landscape io](https://cloud.githubusercontent.com/assets/956109/14301773/c76cc4ca-fb9a-11e5-8656-9f89f81efba7.PNG)

**Comment by carlio** [comment]
I've completely upgraded the hardware and worker logic in the last month so I'm fairly certain this was actually Landscape just not queueing jobs properly. Let me know if it happens again, but given the hardware woes in March/April I'm fairly certain it's now fixed.
