### ISSUE TITLE
PRs and new commits are not getting detected since yesterday

### ISSUE THREAD

**Issue by mistercrunch** [landscapeio/landscape-issues#223]
On this repo: https://landscape.io/github/airbnb/caravel a sample PR:
https://github.com/airbnb/caravel/pull/313

I didn't change the settings in the repo and haven't touched `.landscape.yml` or anything of that nature, so I'm not sure what's going on.

Please help as this service is super useful and only after a month of using the service I can't live without it! I wanted to convince my employer to deploy it on our private python repos!

**Comment by carlio** [comment]
@mistercrunch Turns out the rabbitmq server died so all the workers just stopped for a while. I finally figured that out and restarted it, and things are working now, but it will take a while to catch up! I'll keep an eye on it tonight and hopefully things will have caught up soon.

**Comment by mistercrunch** [comment]
Looks like it may be down again. Are you guys using celery? We've found that using redis in place of rabbitmq to power celery made things much easier for us at Airbnb for this project:
https://github.com/airbnb/airflow

**Comment by mistercrunch** [comment]
@carlio all my PRs look yellow-brown since the landscape jobs don't get picked up... Where are you guys communicating about the on going issues? Do I need to do something on my side?

I'm very grateful for this service and already can't live without it!!!

**Comment by carlio** [comment]
@mistercrunch Thanks! Regarding your first question, I did try using redis once but it seemed to cause me some other issues. Will look into it but I've been really happy with rabbitmq. Unfortunately, in this case the disks on that machine failed and it didn't come back after a reboot. Exact same thing happened to the web server too! Talk about some bad luck.

For communication there is a twitter account (https://twitter.com/landscapeio) but I'm not very good at using it. There's also an IRC channel, #landscape.io on freenode, which I tend to be better at using. I will aim to improve this in the future, apologies!

If the PRs don't automatically get picked up, let me know which repo names and I'll manually restart anything that didn't work. I managed to provision new servers so hopefully it'll be back up now.

**Comment by vasily-v-ryabov** [comment]
PRs and even all other commits are not checked for me since May, 5.
For pywinauto/pywinauto repo: https://landscape.io/github/pywinauto/pywinauto
For python-xlib: https://landscape.io/github/python-xlib/python-xlib

It happened at the moment when I really need these checks.

**Comment by carlio** [comment]
Things seem to be up and running again, sorry about this, it has taken a while to get the workers behaving properly. Let me know if you spot any further issues.

**Comment by vasily-v-ryabov** [comment]
This is working for now. Thanks a lot!
