### ISSUE TITLE
Major issue with Repo and Settings.

### ISSUE THREAD

**Issue by killswitch-GUI** [landscapeio/landscape-issues#224]
Currently, I'm having issues with my account and adding a repo. I have tried to add my repo a few times and every time it just hangs for a day on the "Checking out" phase. I'm also greeted by a "server (500)" when attempting to access my Settings within Landscape IO. I also tried to reset my oAuth settings within GitHub with no success. Am I missing something? 
<img width="471" alt="screen shot 2016-04-10 at 10 43 32 am" src="https://cloud.githubusercontent.com/assets/8761706/14410949/7d294600-ff09-11e5-99b7-826d2f1a0a4d.png">
The interesting part is this repo was working not only a few days ago. one thing I did notice that was odd, landscape has been displaying "Synchronising with GitHub: Waiting..." for a bit as well. Thanks for any help!

**Comment by carlio** [comment]
@killswitch-GUI Thanks for the report - turns out the rabbitmq server died so all jobs/workers were stuck for a while. That's fixed now but it will take a while to catch up with the queue. I'll restart the repository checking too once the queue dies down a bit. Sorry!

**Comment by killswitch-GUI** [comment]
@carlio thanks so much man. I LOVE this platform, thanks for all your hard work!
