### ISSUE TITLE
repository missing

### ISSUE THREAD

**Issue by ashwin31** [landscapeio/landscape-issues#226]
Hi,

I tried to add my public repository to landscape but its not showing in the list. I did re-sync few times but no use.

https://github.com/MicroPyramid/IAM-Manager 

help me to add it to landscape

**Comment by wolfy1339** [comment]
Having the same problem

**Comment by carlio** [comment]
@ashwin31 @wolfy1339 Are you still having this issue? It seems like the repo is in the DB now so either it just took a while to sync (been replacing hardware for workers recently) or if it's still a problem let me know!

**Comment by ashwin31** [comment]
@carlio no, it seems resolved. Thank you.
