### ISSUE TITLE
404 on configuration doc page

### ISSUE THREAD

**Issue by tomschr** [landscapeio/landscape-issues#229]
Under the "Configuration" link (sidebar on the left) you can find this text:

> Configuration
> 
> On the right you can see the configuration information that was used for check NUMBER.
> 
> You cannot change the configuration settings here. Configuration is controlled by a .landscape.yaml file in your project root. Read more in the the Landscape Configuration Documentation. 

The "Landscape Configuration Documentation" points to http://docs.landscape.io/configuration.html, however this page doesn't exist.

**Comment by carlio** [comment]
Fixed now, https://docs.landscape.io/configuration.html ! Thanks for the report. I found an errant quote in the nginx config file...
