### ISSUE TITLE
"Prospector execution failed" issue has appeared again, checks are not running

### ISSUE THREAD

**Issue by vasily-v-ryabov** [landscapeio/landscape-issues#235]
https://landscape.io/github/python-xlib/python-xlib

**Comment by benoit-pierre** [comment]
This might be related to encoding issues with `Xlib/protocol/display.py`, as prospector fails locally too with `prospector --die-on-tool-error Xlib/protocol/display.py`,  see https://github.com/landscapeio/prospector/pull/174

**Comment by vasily-v-ryabov** [comment]
Probably workers should be restarted after merging https://github.com/python-xlib/python-xlib/pull/40 to check if this is the case.

**Comment by vasily-v-ryabov** [comment]
Seems working on recent commits. Thanks a lot, @benoit-pierre!

**Comment by carlio** [comment]
@vasily-v-ryabov @benoit-pierre Ah brilliant thanks!  I will go and merge that PR now, that does seem to be an oversight (and proof I need to write some more tests...), cheers :cake:
