### ISSUE TITLE
change in health for PR ignores updates to master

### ISSUE THREAD

**Issue by ahnitz** [landscapeio/landscape-issues#236]
It seems from experimentation that the change in health given in a PR (which may fail the PR if enabled) is based on taking a diff of the originating branch against master. This isn't what I think people might expect to happen, however, as the merge command itself and other tools such as travis-ci, apply the patches to the top of master first. 

This behavior is problematic for repositories that are changing quickly, and for which a PR may be based slightly behind master. In the following example, the health report complains about issues in a file which no longer exists on master, but does in the branch of the PR only becuase a recent commit to master removed the file.

https://landscape.io/diff/391467

**Comment by carlio** [comment]
This will be fixed with the new PR handling code - now, an update to the incoming branch _and also_ updates to the base branch will create a new comparison. It's new so please re-open this issue or let me know if strange things occur but I think this will work as expected now.
