### ISSUE TITLE
AWS Keys False Positive

### ISSUE THREAD

**Issue by Fuchida** [landscapeio/landscape-issues#24]
Landscape seems to see these as AWS keys, it's commit JSON data from Github and Bitbucket

![screen shot 2014-01-04 at 12 23 19 pm](https://f.cloud.github.com/assets/835396/1845097/78fc1c42-756d-11e3-970c-5c52a04d8bb2.png)

**Comment by carlio** [comment]
Ah whoops. The check is a little overzealous. It has been fixed now to require 'aws' to be present somewhere too.

Thanks for the bug report!

**Comment by Fuchida** [comment]
Good deal  and thanks for the fix !
