### ISSUE TITLE
Pull request checks are getting stuck

### ISSUE THREAD

**Issue by Chlodochar** [landscapeio/landscape-issues#240]
We just set up Landscape for https://github.com/AHAAAAAAA/PokemonGo-Map.

However, the checks that are done on pull requests stay in 'pending' status. Manually triggering a check on the master branch works as expected. See for instance: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2094#partial-pull-merging

The details link also does not lead to a progress or check page, but to the overview of the PokemonGo-Map project on Landscape.

Any idea what is happening?

**Comment by carlio** [comment]
Seems like one of the checkers got stuck and just did nothing for a few hours, sorry about that. I brought up 2 new ones to get through the backlog.

**Comment by carlio** [comment]
Think this is fixed now, the job queue is empty and all the PRs on  AHAAAAAAA/PokemonGo-Map seem to have caught up and new ones are working. Please re-open if you see any more strangeness!

**Comment by Chlodochar** [comment]
@carlio Seems to be working great now! Thanks!

**Comment by Chlodochar** [comment]
We're seeing again a lot of PRs that are stuck on landscape.io. It seems 50% of the PRs are getting stuck: https://github.com/AHAAAAAAA/PokemonGo-Map/pulls

Any idea what is going on?

(BTW: can't reopen)
