### ISSUE TITLE
Landscape-bot does not comment on PR

### ISSUE THREAD

**Issue by petricm** [landscapeio/landscape-issues#241]
After landscape passes the landscape-bot does not comment on PR, despite the settings are set to comment on PRs e.g. https://github.com/DIRACGrid/DIRAC/pull/3052

**Comment by petricm** [comment]
Dear @carlio what is the status of this issue?

**Comment by bittner** [comment]
@carlio Any news on this? Just stumbled upon this issue in https://github.com/behave/behave-django/issues/19. (We still need to check whether we have all required settings set on Landscape though.)

It was still working on 27 Apr 2015 in https://github.com/pytest-dev/pytest-django/pull/232. I don't see it in more recent PRs of the same repo, though.

**Comment by petricm** [comment]
@carlio @bittner , no we still don't get comments on PRs from the bot. e.g. https://github.com/DIRACGrid/DIRAC/pull/2995

**Comment by carlio** [comment]
Working on it, haven't figured out the reason yet but getting there, apologies! @petricm @bittner
