### ISSUE TITLE
Landscape fails with "Failure reason: unknown"

### ISSUE THREAD

**Issue by grzanka** [landscapeio/landscape-issues#242]
Repository under consideration: https://landscape.io/github/DataMedSci/pymchelper/61

I've tried to repeat the jobs, but in all cases I've got following error:

```
Check number 61 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.

Failure reason: Unknown

We don't know exactly why this error happened yet
```

**Comment by carlio** [comment]
@grzanka Fixed now, and all the checks ran. Turns out one of the checkers got stuck in a zombie state so was just starting then doing nothing.
