### ISSUE TITLE
Build stuck

### ISSUE THREAD

**Issue by jarifibrahim** [landscapeio/landscape-issues#246]
Build stuck for the following PR
https://github.com/lewismc/podaacpy/pull/56

I had forced pushed to remove a commit.

**Comment by grzanka** [comment]
I experience the same issue here:
https://github.com/DataMedSci/beprof/pull/89

**Comment by grzanka** [comment]
Also here:
https://github.com/DataMedSci/pymchelper/pull/75

**Comment by carlio** [comment]
This should be fixed now - and it is going through and un-sticking all the PRs that did not get set, although if they're already merged or closed it won't do anything. Sorry about this, and if you see anything odd with new PRs please re-open this issue!
