### ISSUE TITLE
Github displays landscape test as in progress, while they are finished

### ISSUE THREAD

**Issue by grzanka** [landscapeio/landscape-issues#247]
Some of the landscape tests were stucked for this PR:
https://github.com/DataMedSci/pymchelper/pull/74

I've manually restarded them in Landscape, but in github I still see them as being in progress

**Comment by carlio** [comment]
Hi @grzanka . I've just finished a complete rewrite of the PR handling code so hopefully this will not happen in the future. I will also get some kind of "go fix any open PRs that are still hanging" stuff done today. Apologies for this, the workload just got away from the servers and things backed up.
