### ISSUE TITLE
Landscape jobs get 'stuck' and then PR merges are left 'waiting'

### ISSUE THREAD

**Issue by brifordwylie** [landscapeio/landscape-issues#248]
So our project will do a build check and a landscape check before letting the PR merge. In the last week or so we're getting a lot of 'hung' jobs and so the check never comes back for the PR.

https://landscape.io/github/kbandla/dpkt

Can we delete/remove/restart those jobs is any way?

**Comment by fpietka** [comment]
landscape.io is a great tool, I hope this issue won't be too hard to solve.

**Comment by carlio** [comment]
I've tried a few fixes and what it comes down to is that the workers have too much to do! It's up to 7220 being checked now and so things get delayed for quite a while. I'm rewriting a lot of the PR handling logic because I understand how frustrating this is.

**Comment by carlio** [comment]
Should be better now, just released a complete rewrite of the PR handling jobs. Please reopen if you see anything odd but this is now split up such that future jobs won't hang like this, and I'm going to figure out how to go back and fix any stuck past ones.

**Comment by fpietka** [comment]
@carlio thanks a lot
