### ISSUE TITLE
Exclude files and dirs in .landscape.yaml?

### ISSUE THREAD

**Issue by rafalp** [landscapeio/landscape-issues#25]
It would be nice if I could exclude certain directories from landscape reports.

For example I'm using Sphinx for docs and landscape tests it's autogenerated conf.py:

https://landscape.io/github/rafalp/Misago/134/modules/docs/conf.py#L15

I would like to exclude this form process, is it possible?

**Comment by carlio** [comment]
Is is not currently possible, but this definitely would be a useful feature, so I will work on getting it in soon.

**Comment by nijel** [comment]
:+1: Also being dragged down by generated code such as South migrations.

**Comment by nijel** [comment]
South migrations now should be ignored by prospector for Django projects, see https://github.com/landscapeio/prospector/issues/12

**Comment by carlio** [comment]
There are now two more configuration options: `ignore-paths` and `ignore-patterns`. These allow you to ignore directories and files based on their path or a regular expression. See the docs (at the bottom) for more info: http://landscape.io/pages/docs

**Comment by carlio** [comment]
PS @nijel [weblate](https://landscape.io/github/nijel/weblate/144) went from 68% to 93% as a result of this fix :)
