### ISSUE TITLE
New StackOverflow tag: landscape.io

### ISSUE THREAD

**Issue by Paebbels** [landscapeio/landscape-issues#250]
Hello Carl,

StackOverflow got an new `landscape.io` tag. Please review and extend my initial excerpt and wiki text.
=> http://stackoverflow.com/questions/tagged/landscape.io

Should there be a `prospector` tag, too? Otherwise, please suggest it as a possible synonym.
I have found only one question regarding prospector.

Kind regards
    Patrick Lehmann

**Comment by carlio** [comment]
Thanks @Paebbels ! Not sure what I can do about this as my stackoverflow score is woefully small but the summary looks good to me as is.  I guess if there are enough questions appearing about prospector, then a new tag makes sense but for now might as well just wait and see how much activity there is.

MfG!
Carl
