### ISSUE TITLE
Landscape.io throws 500 error viewing change list 

### ISSUE THREAD

**Issue by tedmiston** [landscapeio/landscape-issues#255]
Attempting to view this repo's diff list now throws a 500 error.

https://landscape.io/github/tedmiston/challenges/22/diff

I have a hunch it may be due to specifying Python 3 in the `.landscape.yml` config, while some of the scripts in the repo were written in Python 2 and haven't been explicitly updated for Python 3 yet.  (This is something I'm fixing.)  Still, I wouldn't expect the server to throw a 500 for this.

Note that the 500 is only seen on the Changes page and the Style page.  The errors page with 7 errors seems to load fine.  The Smells page with 0 smells also loads fine.

**Comment by carlio** [comment]
Seems like this is some GitHub API quirk due to having '?' as a folder name. I fixed it, I think!

**Comment by tedmiston** [comment]
Works on my end too.  Thank you!
