### ISSUE TITLE
Landscape generates invalid MD link for badge

### ISSUE THREAD

**Issue by rafalp** [landscapeio/landscape-issues#26]
Landscape allows me to make badge to put on my repo which is nice (everybody loves badges ;)), but link it gives you to use for MD documents is something like this:

```
[![Code Health](landscape.io/github/rafalp/Misago/future/landscape.png)](landscape.io/github/rafalp/Misago/future)
```

This link looks like this on Github:
[![Code Health](landscape.io/github/rafalp/Misago/future/landscape.png)](landscape.io/github/rafalp/Misago/future)

Code maker should prepend "https://" to landscape.io

**Comment by carlio** [comment]
Caused by the same thing as #27. Fixed now, thanks!
