### ISSUE TITLE
Unknown landscape.io internal error "This is almost always due to a bug in Landscape - we have been notified. Sorry about that."

### ISSUE THREAD

**Issue by bowenli86** [landscapeio/landscape-issues#263]
https://landscape.io/github/phoenixjiangnan/incubator-airflow/1
says:
"
Check number 1 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.
Failure reason: Unknown
We don't know exactly why this error happened yet
"

Can you please fix this?

**Comment by bittner** [comment]
I am also seeing this error. I see it for several repositories, e.g. [behave-django](https://landscape.io/github/behave/behave-django), [django-apptemplates](https://landscape.io/github/bittner/django-apptemplates), [django-analytical](https://landscape.io/github/jcassee/django-analytical).

![landscape-build-failing](https://user-images.githubusercontent.com/665072/35526756-c9dc1bb8-0528-11e8-80a7-c12edf7f413a.png)

Cc https://github.com/behave/behave-django/issues/58.

**Comment by bittner** [comment]
Any update on this?

**Comment by carlio** [comment]
Yeah so I am basically rewriting a lot of Landscape right now to handle so many dependency changes. It's on the way...
