### ISSUE TITLE
Server Error 500 when access pull request details page

### ISSUE THREAD

**Issue by jfunez** [landscapeio/landscape-issues#269]
Link: https://landscape.io/github/scieloorg/opac_ssm/pulls/47
Shows: ``Server Error (500)`` page
I can see other pages like PR list page, and everything else.

**Comment by FredStober** [comment]
I see the same issue with: https://landscape.io/github/grid-control/grid-control/pulls/38

**Comment by skudriashev** [comment]
Same here https://landscape.io/github/apache/incubator-airflow/pulls/2512

**Comment by skudriashev** [comment]
Guys, is anyone looking into this issue?
