### ISSUE TITLE
Support for Python 3.6

### ISSUE THREAD

**Issue by bagrat** [landscapeio/landscape-issues#272]
The new syntax introduced by Python 3.6 are identified as `invalid syntax`. E.g.

* variable annotations
* f-strings
* etc

Would be great to have support for Python 3.6.

**Comment by abbec** [comment]
Would really love to see this too

**Comment by csko** [comment]
+1

**Comment by Riverfount** [comment]
My [package](https://landscape.io/github/Riverfount/cpf_validator) had 25 percentage point decrease in its health because I used the f-string syntax, that's terrible!!

**Comment by ovv** [comment]
Any update on this ?
