### ISSUE TITLE
Pull request report shows issues unrelated to PR

### ISSUE THREAD

**Issue by mattclay** [landscapeio/landscape-issues#274]
Some pull request reports are showing issues unrelated to changes in a PR:

https://landscape.io/github/ansible/ansible/pulls/20509

It reports 196 new and 268 fixed issues across many files. However, looking at the PR:

https://github.com/ansible/ansible/pull/20509

It only changes 2 files.

Is the analysis being performed after merging the PR to the HEAD of the upstream branch, or is it comparing changes between the (possibly stale) branch the PR is based on and HEAD of the upstream branch?

**Comment by carlio** [comment]
This comparison was between 85d7839... on ansible/ansible and df3ae0787f... on the upstream - so basically the latest of both at the time the comparison ran. Therefore this is a bug in the comparison logic, it should not have throw those up, I'll try to figure out what went on.
