### ISSUE TITLE
Signup error, deplicate parameter

### ISSUE THREAD

**Issue by blatinier** [landscapeio/landscape-issues#275]
I signed up seconds earlier, and I encountered a problem during the process which prevented me from completing signup.
After authorizing landscapeio on github, I was redirected to a page where the URL contained the parameter "state" twice. An error is displayed specifying that there can only be one parameter of the same name.

Modifying the URL and refresh allowed me to complete signup.

**Comment by carlio** [comment]
This is strange, somebody else emailed me earlier today and I found this problem but nothing has changed in the signup/login code for a long time. I'm looking into it, don't really know where to start yet, thanks for the report!

**Comment by chiffa** [comment]
Same thing here

**Comment by carlio** [comment]
Ok, figured this out, fixed now!
