### ISSUE TITLE
Allow to exclude a directory from analysis

### ISSUE THREAD

**Issue by sueastside** [landscapeio/landscape-issues#28]
I have some Thrift generated python in my project, which brings my whole score down.

Is there some way to exclude directories or files from being checked by landscape?

Thank you.

**Comment by carlio** [comment]
There isn't currently, but I will work on it. I'm going to close this issue as it's a duplicate of #25 - please follow updates there!

**Comment by carlio** [comment]
There are now two more configuration options: `ignore-paths` and `ignore-patterns`. These allow you to ignore directories and files based on their path or a regular expression. See the docs (at the bottom) for more info: http://landscape.io/pages/docs
