### ISSUE TITLE
Landscape runns never finish

### ISSUE THREAD

**Issue by cod3monk** [landscapeio/landscape-issues#289]
I have been unable to get a result on landscape.io for github/RRZE-HPC/kerncraft for some time. Many commits have taken place in between.

Is there anything that I can to correct that issue?

**Comment by fabiocaccamo** [comment]
Same problem, this is my repo: https://github.com/fabiocaccamo/python-codicefiscale

**Comment by cod3monk** [comment]
Landscape.io seems to be back on track. Thanks!
