### ISSUE TITLE
Incorrect error when subclassing external project

### ISSUE THREAD

**Issue by wolph** [landscapeio/landscape-issues#29]
As can be seen here: https://landscape.io/github/WoLpH/django-admin-generator/6/messages/error#L318

I am getting the error `Use of super on an old style class`, while the class is actually inheriting object somewhere down the road. Have I stumbled upon a bug or am I misunderstanding the way landscape checks?

**Comment by carlio** [comment]
That is strange. It's definitely a bug, I will look into it. Thanks for the report!

**Comment by wolph** [comment]
I have probably figured out some of the problem, it seems the dependencies are not being figured out correctly.

According to this page my project `Uses: Nothing`: https://landscape.io/github/WoLpH/django-admin-generator/7/config

While my latest commit added an `install_requires`: https://github.com/WoLpH/django-admin-generator/commit/b75cb935a4d66680503613a7564d00193002bcf2

**Comment by carlio** [comment]
I think this is a combination of bugs, but mostly it's because Landscape does not install dependencies (yet). This means that it can't inspect the parents of your class if they're not in your project. However, it should just ignore this, rather than warning.

That "uses: nothing" is more for "tweaks" that Landscape does to improve checks if you use Celery or Django. I realise that's not a good name though.

**Comment by carlio** [comment]
I've opened a more generic issue to handle this here: https://github.com/landscapeio/landscape-issues/issues/31

**Comment by wolph** [comment]
But the project _is_ using Django so shouldn't it detect that? Or is that only for specific cases?

**Comment by carlio** [comment]
Ah sorry, I misunderstood the issue. Landscape does indeed detect that the project uses Django - I think the real problem is an underlying one where it is not handling the subclassing style of Django (which uses `six`). I'll spend some more time digging

**Comment by carlio** [comment]
It's the 1 year anniversary of this issue so I'll close

**Comment by wolph** [comment]
I'll run a new test to see if it's solved :)
