### ISSUE TITLE
Endless run now since 24 hours

### ISSUE THREAD

**Issue by spaceone** [landscapeio/landscape-issues#290]
There are no status information. My build now runs since more than 24 hours.
https://landscape.io/github/univention/univention-corporate-client-integration/2

**Comment by algorys** [comment]
Have the same problem with a new repository added:

https://landscape.io/github/algorys/cmakeconverter/4

All build seems stucks.

**Comment by nicolaschotard** [comment]
I also have the same problem with the following repository added yesterday: 

https://landscape.io/github/nicolaschotard/stackyter

**Comment by hsiaoyi0504** [comment]
Also for me https://landscape.io/github/NAL-i5K/genomics-workspace

**Comment by spaceone** [comment]
It seems fixed.

**Comment by spaceone** [comment]
It seems not fixed when adding a new repository. But the repository I added a week ago is now working.

**Comment by hsiaoyi0504** [comment]
The repo I added a week ago is still not working.

**Comment by nicolaschotard** [comment]
Same problem with a new repo added a few days ago https://landscape.io/github/nicolaschotard/bpz

**Comment by IceflowRE** [comment]
Same here: https://landscape.io/github/IceflowRE/MR-eBook-Downloader

**Comment by jonas-eschle** [comment]
Same here: https://landscape.io/github/Phynix/yamlloader

**Comment by toolswatch** [comment]
same here for at least 10 DAYS !!!!!
https://landscape.io/github/toolswatch/vFeed/33
https://landscape.io/github/toolswatch/vFeed/32
https://landscape.io/github/toolswatch/vFeed/31
https://landscape.io/github/toolswatch/vFeed/30

It seems i cant even stop those checks !!

**Comment by spaceone** [comment]
Still waiting since month. It would be nice if a maintainer would react upon this.
