### ISSUE TITLE
landscape.io hung at "Running First Check"

### ISSUE THREAD

**Issue by makhomed** [landscapeio/landscape-issues#292]
I add two new repositories to landscape.io,

https://landscape.io/github/makhomed/autobackup
and https://landscape.io/github/makhomed/fabrix

but landscape.io hung at "Running First Check"...

How I can fix this issue?

**Comment by SunyataZero** [comment]
It's stuck on "Running..." on an old commit for me, but it has worked before. November 4 was the last date where an analysis was completed

**Comment by makhomed** [comment]
I stop using landscape.io service, so closing ticket. 
Landscape.io is very slow and see only old commits in repository. 
I switch to using prospector from command line:

```bash
#!/bin/bash

pushd /opt/fabrix

prospector --no-autodetect --no-blending --no-external-config --full-pep8 --strictness veryhigh --max-line-length 160 | less

popd
```
