### ISSUE TITLE
landscape.io stuck connecting hooks

### ISSUE THREAD

**Issue by allthatilk** [landscapeio/landscape-issues#293]
None of our repos seem to be able to get past the 'connecting hooks' stage of setup

[https://landscape.io/repository/651902/status](https://landscape.io/repository/651902/status)

**Comment by bwohlberg** [comment]
I have a similar problem, but the repo is stuck in the 'checking out' phase

https://landscape.io/repository/335385/status

**Comment by freude** [comment]
I have similar issue. It is second day I am at the stage of connecting hooks.
https://landscape.io/repository/798927/status

**Comment by freude** [comment]
How have you resolved that issue, guys?

**Comment by bwohlberg** [comment]
See also issue #308. My sense from the long list of open issues without any response is that landscape.io is no longer providing support. Your best option is probably just to switch to one of the many alternative services.

**Comment by jtmoon79** [comment]
Same issue
https://landscape.io/repository/820814/status
