### ISSUE TITLE
Docs link dead

### ISSUE THREAD

**Issue by drdhaval2785** [landscapeio/landscape-issues#295]
https://docs.landscape.io/gettingstarted.html

Gives error

**Comment by yannduran** [comment]
Expanding on the post above, _**'How do I setup Landscape?'**_ gives a 404 error. Not a good start for someone like me that has just discovered Landscape, and no idea how to get started.

**Comment by eyb1** [comment]
So, no documentation then?

**Comment by mabernardo** [comment]
+1
None of the links in https://docs.landscape.io/ is working.

**Comment by yannduran** [comment]
So, no comment from any Landscape team member, and this issue just gets summarily closed?

I guess the developers just don't care.

**Comment by drdhaval2785** [comment]
It seems that landscape.io is also dead now. It shows only Back soon message. Therefore it seems that the developers are not going to pursue these issues.
