### ISSUE TITLE
Top left icon link to /dashboard or home page?

### ISSUE THREAD

**Issue by phalt** [landscapeio/landscape-issues#3]
Most websites have their logo link to the common 'home' page of a website, such as the dashboard or the home page, even if other links are there. Currently the logo doesn't and I instinctively go to click it when I want to return to my dashboard.

It's a small user enhancement which might benefit some users.

**Comment by phalt** [comment]
Update:
I noticed in [this](http://www.reddit.com/r/django/comments/1pw9oi/show_rdjango_landscapeio_hosted_static_code/cd75m91) comment on reddit that you said the link _is_ clickable.

When I go into inspector on Chrome and hover over it, I don't get the `<a>` tag at all, instead it is showing this DOM element:

```
<div class="collapse navbar-collapse navbar-responsive-collapse">
```

It seems you're using bootstrap, try putting an `<a>` tag around the `<div id="logo" class="navbar-header">` div within the nav bar, does that make sense?

There is only so much debugging I can do with the inspector, hope this helps :+1:

**Comment by carlio** [comment]
Yes, it was a bit strange, there was an `A` tag around the logo but it turned out that the `UL` navigation on the right side was hiding it due to that `navbar-collapse` div. I just removed the div since it's not actually necessary, and now it works, hurrah!

Thanks for your help :cake: and you can now click on the logo

**Comment by phalt** [comment]
Glad I could help :) Loving the site, I'll be using it regularly! It helped point out issues that flake8 didn't even find. :smile:
