### ISSUE TITLE
SVG badges

### ISSUE THREAD

**Issue by mikebryant** [landscapeio/landscape-issues#30]
Can we get SVG badges like the ones here: http://shields.io/ (So they can all be of a nice consistent style, and render well on high resolution displays.)

**Comment by carlio** [comment]
That looks awesome. I'll get right on it!

**Comment by carlio** [comment]
Done! The badges are now SVG based - the URLs have remained the same so no need to update your README.md . I think GitHub caches the PNGs for a while though, so you may not seen the update immediately.

**Comment by asl97** [comment]
@carlio i am fine with backward compatibility, but i don't really like the fact that a link which end with .png point to a .svg source, it is bad even if it does works.

it would be better if, for example (link taken from issue #51), https://landscape.io/github/luanfonceca/speakerfight/master/landscape.svg works as well

**Comment by carlio** [comment]
@asl97 good point. I've changed it so the links provided in the badge list page use SVG as an extension. The old PNG URLs still work and 301 to the new SVG URLs too.
