### ISSUE TITLE
Landscape fails running Prospector correctly

### ISSUE THREAD

**Issue by maxfischer2781** [landscapeio/landscape-issues#300]
It seems that there is still an issue when Landscape uses Prospector:

> Check number 141 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.
> **Failure reason: Prospector execution failed**
> The checking tool, prospector, did not complete correctly

[Check 141 for chainlet devel](https://landscape.io/github/maxfischer2781/chainlet/141)

I've checked common causes reported in previous tickets: 
- .landscale.yaml seems properly formatted https://github.com/landscapeio/landscape-issues/issues/243
- vulture is not in the yaml https://github.com/landscapeio/landscape-issues/issues/288
- prospector properly runs locally https://github.com/landscapeio/prospector/issues/197
but none of them seem to apply.

Any help in fixing or debugging would be appreciated. Looking forward to using landscape.io again. :)

**Comment by ecederstrand** [comment]
Having a similar issue. Most times I get a generic [`Failure reason: Unknown`](https://landscape.io/github/ecederstrand/exchangelib/500) but once in a while I get the same [`Prospector execution failed`](https://landscape.io/github/ecederstrand/exchangelib/472).

**Comment by AMDmi3** [comment]
[Same](https://landscape.io/github/repology/repology/970) here

**Comment by attzonko** [comment]
I have had the same issue as well ([see here](https://landscape.io/github/attzonko/mattermost_bot/10)). Is it possible it is related to being a fork? The original repo I forked from does not seem to have this issue.

**Comment by maxfischer2781** [comment]
@attzonko All my failed repos are original repos, not forks. I also observe this for original repos of other projects.

**Comment by AMDmi3** [comment]
I too have the problem with original repository.

@carlio ping?

**Comment by algorys** [comment]
The same for me for 2 repos ([here](https://landscape.io/github/algorys/cmakeconverter) and [here](https://landscape.io/github/Alignak-monitoring-contrib/alignak-app)). I've tried to re run many time but build does not work.

**Comment by maduck** [comment]
bump @carlio: same [here](https://landscape.io/github/maduck/libnagios/15)

**Comment by peterbrittain** [comment]
I just checked my project too.  It has been broken since Jan with the exact same symptoms.  Is there anything happening here?  Can I help?

**Comment by pennyarcade** [comment]
Same problem here.

It would be a great quick fix to make the prospector error message/stack trace available so your users can try to debug the problem. I am pretty sure I suggested that before.

**Comment by pgularski** [comment]
Any updates on this one and #308 ? I'm having the same problem [here](https://landscape.io/github/pgularski/pysm) .
