### ISSUE TITLE
Landscape fails with "Failure reason: unknown"

### ISSUE THREAD

**Issue by FedeG** [landscapeio/landscape-issues#308]
Repository under consideration: https://landscape.io/github/eventoL/eventoL/192

I've tried to repeat the jobs, but in all cases I've got following error:

```
Check number 192 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.
Failure reason: Unknown

We don't know exactly why this error happened yet
```

**Comment by fabiocaccamo** [comment]
I have the same problem with this repo: [django-treenode](https://github.com/fabiocaccamo/django-treenode)

**Comment by giffels** [comment]
Same problem with https://github.com/giffels/CloudStackAIO. 

Thanks and best regards,
Manuel

**Comment by ahnitz** [comment]
Same problem. https://landscape.io/github/gwastro/pycbc

**Comment by nolanbconaway** [comment]
Same problem https://landscape.io/github/AusterweilLab/jarjar/14

**Comment by maxfischer2781** [comment]
See also issue #300.

**Comment by spaceone** [comment]
Same problem https://landscape.io/github/spaceone/httoop/121
