### ISSUE TITLE
readme badge doesn't work (certificate error)

### ISSUE THREAD

**Issue by akoidan** [landscapeio/landscape-issues#311]
Repository [pychat](https://github.com/akoidan/pychat) has [landscape.svg](https://landscape.io/github/akoidan/pychat/master/landscape.svg) badge, which github caches into camo. If you access badge via browser it works, however camo is unable to access the badge. Furthermore if I try to get it from console i get:

> : wget  https://landscape.io/github/akoidan/pychat/master/landscape.svg
> --2019-04-16 11:20:59--  https://landscape.io/github/akoidan/pychat/master/landscape.svg
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving landscape.io (landscape.io)... 78.46.108.86
> Connecting to landscape.io (landscape.io)|78.46.108.86|:443... connected.
> ERROR: The certificate of ‘landscape.io’ is not trusted.
> ERROR: The certificate of ‘landscape.io’ doesn't have a known issuer.
>

**Comment by hoefling** [comment]
Same issue is also observable when rendering the readme on PyPI; an example: [`devpi-client-extensions`](https://pypi.org/project/devpi-client-extensions/) project page.

**Comment by hoefling** [comment]
Same issue is also observable when rendering the readme on PyPI; an example: [`devpi-client-extensions` project page](https://pypi.org/project/devpi-client-extensions/).

**Comment by matthewfeickert** [comment]
This is also happening for pyhf both on [GitHub](https://github.com/diana-hep/pyhf) and [PyPI](https://pypi.org/project/pyhf/). However, it is working on our [GitHub pages hosted docs](https://diana-hep.org/pyhf/).

cc @kratsg @lukasheinrich
