### ISSUE TITLE
Lanscape and Python 3 ?

### ISSUE THREAD

**Issue by mfe** [landscapeio/landscape-issues#32]
Can I set up a python version in the configuration file ?

Some Python 3 new features are considered as errors...
Ex: print("") --> Unnecessary parens after 'print' keyword

Can't find the info in [docs](https://landscape.io/pages/docs).

Thanks !

**Comment by ricomoss** [comment]
+1

Yup...was coming to create the same issue.

There are also complaints about "Old Style Classes" but there are only new style classes in P3.

**Comment by carlio** [comment]
Unfortunately right now Landscape only supports Python2. py3k support is in the works; the biggest problem is not so much detecting problems, but in presenting it. There are a few things on the roadmap in front of this - private repo support for one, #31 to better use dependencies. However it will be done.

**Comment by carlio** [comment]
Actually, thinking about it - how useful would a "Python 3 only" mode be for you? The main problem encountered so far is that lots of libraries want to be compatibile with both, which is difficult to store and present in a user friendly way. But a binary "Python 2 or 3" might be a lot easier.

**Comment by ricomoss** [comment]
Having a binary P2 or P3 could be very useful.  My open source projects support both P2 & P3 and I can see that as being troublesome for you.  When I start new stand-alone projects, or when I teach someone Python I always use P3.  Always.

**Comment by mfe** [comment]
+1, Python 2 or Python 3 could be already really useful.

On Thu, Apr 10, 2014 at 12:59 AM, Rico Cordova notifications@github.comwrote:

> Having a binary P2 or P3 could be very useful. My open source projects
> support both P2 & P3 and I can see that as being troublesome for you. When
> I start new stand-alone projects, or when I teach someone Python I always
> use P3. Always.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/landscapeio/landscape-issues/issues/32#issuecomment-40026776
> .

## 

[image: Mikros Image: Open Source]
_Marie Fétiveau_
Color and D-cinema R&D Engineer

+33 1 55 63 11 00
mfe@mikrosimage.eu xxx@mikrosimage.eu

_Mikros Image /_
Digital Post-Production for Video and Film

www.mikrosimage.eu

**Comment by zkanda** [comment]
Any news on this one?

**Comment by make-github-pseudonymous-again** [comment]
+1

**Comment by jromang** [comment]
Would also be interested by this !

**Comment by abingham** [comment]
I'd like Python 3 support, too. Ideally I could tell landscape that my project is Python 2 only, Python 3 only, or both. It might be useful to be able to specify major.minor versions as well, though I don't have a real motivating case for that at the moment.

**Comment by Kuniwak** [comment]
> how useful would a "Python 3 only" mode be for you? 

+1

**Comment by The-Compiler** [comment]
A python3-only mode would be sufficient for me.

Maybe a solution for "hybrid" projects would be to be able to add the same project twice, once with python2 and once with python3?

**Comment by pradyunsg** [comment]
Hey Guys!

Firstly +1 to Py3 support.

IMHO, having 2 binary options, one for Py2 other for Py3 and enforcing that at least one of them is ON seems like the best way to support multi-version as well as version specific projects.

**Comment by buxx** [comment]
:+1: for  "Python 3 only" to !

**Comment by hkupty** [comment]
:+1:

**Comment by fabiencastan** [comment]
+1

**Comment by tiagoantao** [comment]
+1

**Comment by harvimt** [comment]
:+1:

**Comment by jvlomax** [comment]
+1 
It's annoying having an error because I apparently don't use super() correctly

**Comment by andras-tim** [comment]
I have got some errors with python3 format:
- `def get_name(self, id: int) -> string:` => **invalid syntax**
- `#!./flask/bin/python` => **Could not parse file**
- `import string` => **Could not parse file**

You can see this like errors at: https://landscape.io/github/andras-tim/StoreKeeper/7/messages/error

**Comment by bedekelly** [comment]
+1 on the Python3-only mode, I'm getting SyntaxErrors on lines like this:

`def __init__(self, *names, title=None, subtitle=None):`

Looks like it's related to [PEP 3102](https://www.python.org/dev/peps/pep-3102/).

Just a thought, couldn't we use the shebang line to explicitly state what version of Python we want it to be parsed with? `/usr/bin/env python3` or `/usr/bin/env python2`, for example?

**Comment by ids1024** [comment]
+1

It would be good to also specify a minimum version of python 2/3, since one of the errors landscape is giving my is that `yield from` is invalid, while it was added in python 3.3., while some projects will want to support older versions and not just the latest.

**Comment by rshipp** [comment]
@bedekelly shebang would only work for scripts, library files usually don't include that.

**Comment by bedekelly** [comment]
@rshipp Sure, but it wouldn't break if the shebang wasn't there; just something to think about in terms of auto-detection.

**Comment by andras-tim** [comment]
As far as I know, the **landscape.io** isn't support _Python 3_ now! If your code is _Python 2_ compatible, the results are quite good, but the code parser, static analyser (`pylint`), ... are ran by _Python 2_ interpreter!

**Comment by pulsedemon** [comment]
+1 I would love python 3 only mode.  I'm using python 3 for my django project, and landscape still seems useful despite some of the problems it finds since it is interpreting the code as python 2, but adding python 3 support would be a huge plus.

**Comment by cyroxx** [comment]
+1 Adding Py3 support would be a big plus. While libraries might still need to support Python (2.6 and) 2.7 for some time, any newly developed applications should be implemented in Py3 from the start. Those are the ones that will definitely benefit from Py3 support.

To me, "Py3-only mode" would be the minimal requirement, otherwise users with new projects will soon turn their back to landscape.io. Any possibility to put a project under py3 _and_ py2 test would be nice-to-have.

@carlio Do you have any update on this issue? It seems there is much attention on this one.

**Comment by kylepjohnson** [comment]
+1

I wish lack of Python 3 support had been made clearer in the docs, before I invested time in landscape.io.

**Comment by xanderdunn** [comment]
+1 for python only mode.

**Comment by robvdl** [comment]
Really need to do something about this, I had to stop using landscape, because my project is Python 3 only, lots of projects coming out today that are Python 3 only, this is a huge problem.

**Comment by andras-tim** [comment]
I have waited for fix this service, but I realized this is a never completed story.

However there is a good news:
The **Code Climate** ( https://codeclimate.com/ ) has started public beta Python support! I use it for 2 months and I love it. (Thank you for Landscape crew for past working)

**Comment by acutesoftware** [comment]
I have a project in Python 3.4 and it appears to work flawlessly for everything _except_ the super class issue.

http://www.reddit.com/r/Python/comments/375u0v/python_34_flask_lint_issue_use_of_super_on_an_old/

class FactListAPI(Resource):
    def **init**(self):
            #Use of super on an old style class
        self.reqparse = reqparse.RequestParser()
        self.reqparse.add_argument('fact_str', type=str, required=True,
                                   help='No Fact content provided',
                                   location='json')
        super(FactListAPI, self).**init**()
Is there a better way to do this, or is there a way I get suppress this error?

**Comment by harvimt** [comment]
You just got lucky. If you were using more Python 3 only features or
features with different syntax in python 3 (`yield from`, metaclasses,
etc.), you'd probably find more problems.

**Comment by spaceone** [comment]
-1 :-1:

**Comment by ids1024** [comment]
@carlio What's holding this up? I see you mention code that is both py2 and py3, but I would guess that a py3 only mode as you suggested would be simple to add and very useful. I have a couple python 3 only projects using landscape and would like to continue using landscape, but there are incorrect errors because it is testing for py2.

**Comment by adrientetar** [comment]
+1

**Comment by carlio** [comment]
Ok so I was perhaps a bit slow at doing this... But it's getting there. Do any of you have any projects you would like to be guinea pigs to help work out the bugs before I release the feature fully?

**Comment by The-Compiler** [comment]
Glad to hear there's some progress! I could help testing with [qutebrowser](https://github.com/The-Compiler/qutebrowser).

**Comment by carlio** [comment]
@The-Compiler sounds good - I'll add ~~a horrible hack~~ it to the list of projects to be checked with python3 :+1:

**Comment by idlesign** [comment]
@carlio One with cyrillics: https://landscape.io/github/idlesign/pythonz

**Comment by ids1024** [comment]
@carlino That's great to hear! If you have a list, you can add mps-youtube and wikicurses to it.

**Comment by carlio** [comment]
@idlesign Added, but most of the issues were due to including cyrillics without using an encoding declaration (see [PEP0263](https://www.python.org/dev/peps/pep-0263/)), which may be worth doing if you care about python2 at all.

@ids1024 Added both, mps-youtube didn't change much but wikicurses is no longer plagued by "syntax errors" :)

**Comment by idlesign** [comment]
@carlio This one is Py3 only.

**Comment by carlio** [comment]
@idlesign Fair enough :)

**Comment by tiagoantao** [comment]
If you want feedback from biopython, glad to help

**Comment by FrancescoCeruti** [comment]
@carlio Great!
you can try with https://landscape.io/github/FrancescoCeruti/linux-show-player (py3 only)

**Comment by carlio** [comment]
@tiagoantao @FrancescoCeruti thanks, I've added both!

**Comment by Insoleet** [comment]
Great to here that ! :+1: 

You can check sakia wallet - https://landscape.io/github/ucoin-io/sakia , we are working with latest python 3.5 features (async and await keywords notably)

**Comment by carlio** [comment]
@Insoleet This is all working "first class" now, kind of. You can set what Python version your rrojects use  either in the configuration file or by specifying trove classifiers in your `setup.py`. Read more in the full documentation here](https://docs.landscape.io/configuration.html#python-targets-2-3)

The default is still Python2 for now although I have several ideas on how to improve autodetection. The problem is that rright now Landscscape needs a bit of work right now as I got into a traffic accient and broke most of myself (more here https://github.com/landscapeio/landscape-issues/issues/202).  Therefore this should all work but if it does not please have some patience and add an issue. It's very very close, finally! I'm looking forward to improving it to add new cool stuff like "python 3 readiness" or something :)
