### ISSUE TITLE
Landscape ignores some branches

### ISSUE THREAD

**Issue by Bengt** [landscapeio/landscape-issues#33]
I use topic branches and landscape only picks up some of them. Compare: https://github.com/cigroup-ol/metaopt/branches
- `master` works
- `develop` works
- `finite_tasks_fix` works
- `Bengt-StatusDB` fails

~~Since aside from the conventional `master` and `develop` branches, the unconventional `finite_tasks_fix` branch works, landscape seems to work with arbitrarily named branches. `Bengt-StatusDB` has two features, the other branches lack: Capitalization and a dash (`-`) in the name. Might some of that be the issue?~~

**Comment by Bengt** [comment]
I did not have `finite_tasks_fix` checked and when activating it, `Bengt-StatusDB` appeared. So landscape seems to stop suggesting branches when it first encounters one that is not checked, yet. Users might have branches that they never want to check, so this might permanently hinder further branches to be checked.

**Comment by carlio** [comment]
Hi @Bengt - this behaviour is a bug. It should be the case that Landscape detects all branches on GitHub, and starts a new check if a new branch is created. I will investigate further but initially it seems like the background job which synchronises repository state did not pick up the new branch. Thanks for the bug report!

**Comment by Bengt** [comment]
@carlio Thanks for going about this. I noticed that my branches do not get rechecked when I push to GitHub. Is this perhaps related to synchronization and can be handled here or should I open another issue?

**Comment by carlio** [comment]
Could you please check if the Landscape hook is enabled (In https://github.com/cigroup-ol/metaopt/settings/hooks)?

**Comment by carlio** [comment]
There seem to have been a couple of strange behaviours actually, Landscape believes your default branch is 'master' when it is in fact 'develop'. I'll dig more, in the mean time I will just update this issue.

**Comment by Bengt** [comment]
I do not have a web hook for Landscape on GitHub.

**Comment by carlio** [comment]
Aha, that's the problem then. Landscape has incorrectly decided that a hook exists, so it stopped synchronising because it expected to get data via hooks. I've fixed the database state so at least you should see changes appearing now.

I'll look further into how it happened though as this probably affects more than your repository!

**Comment by Bengt** [comment]
Awesome, thanks. I have enabled the service manually and triggered "Test Hook" to deploy a test payload.

**Comment by carlio** [comment]
Ok, that hook definitely came through - thanks! Let me know if you see any other oddities :+1:

**Comment by Bengt** [comment]
The checks have now finished as expected. Will see if I can make some quick fixes to trigger another check.

**Comment by Bengt** [comment]
The new checks are through. The webhook seems to work properly, now.
