### ISSUE TITLE
Comparisons across branches

### ISSUE THREAD

**Issue by Bengt** [landscapeio/landscape-issues#34]
I use topic branches and would like to know whether and where they affect landscape's score. Landscape provides comparisons between commits of one branch, but not between commits of two branches. Initially comparing the HEADs of two branches might be enough, but ultimately selecting an arbitrary commit would be welcome.

**Comment by carlio** [comment]
This is a feature which is on the roadmap (by which I mean the very long TODO list!). It'll require some fairly significant infrastructure changes, as currently all comparisons are generated at the time of the check. Therefore it will probably be some time before I can get around to it, as there are some other priorities in the way, however it will eventually get done.

**Comment by js850** [comment]
this would be very useful.

**Comment by carlio** [comment]
This feature has existed for a while actually - when creating a new branch, it compares to the default branch (typically master, but whatever is set in GitHub preferences)
