### ISSUE TITLE
Allow for exclusion rules

### ISSUE THREAD

**Issue by sigmavirus24** [landscapeio/landscape-issues#35]
Most of my projects are receiving poor grades because of `docs/conf.py` which is auto-generated by Sphinx and not something I wrote. If I could exclude that, I would ❤︎ landscape.io even more.

**Comment by carlio** [comment]
You can twiddle exclusions rules already if you add a `.landscape.yml` file - in your particular case, the `ignore-paths` setting is what you want. Check out https://landscape.io/pages/docs

**Comment by carlio** [comment]
(as an aside, I tihnk that ignoring 'docs' folders by default makes sense, given the number of complaints about that!)

**Comment by sigmavirus24** [comment]
D'oh! I should have checked the documentation first. I was expecting to see it on the overview for the project for some reason. :)

**Comment by carlio** [comment]
In fairness the documentation is currently lacking in my opinion :-)

**Comment by sigmavirus24** [comment]
To be fair, I didn't even look to see if there was any documentation.
