### ISSUE TITLE
Feature Request: force add files for inspection

### ISSUE THREAD

**Issue by bchretien** [landscapeio/landscape-issues#36]
It seems that `landscape` is looking for files with the `.py` extension. However, in some projects, the Python extension may be omitted when files are designed to be installed as programs in `/usr/bin`. Would it be possible to provide a way to add such files in `.landscape.yaml`?

**Comment by ssokolow** [comment]
While it's not ideal for all situations, as a workaround, you can use the setuptools [`console_scripts`](http://pythonhosted.org//setuptools/setuptools.html?highlight=console_scripts#automatic-script-creation) entry point in your `setup.py` instead.

That way, your code stays in `.py` files and `setup.py` generates launcher wrappers on install.

(It also has the added benefit of giving you some Windows convenience hacks for free.)

**Comment by carlio** [comment]
My own personal 'solution' is that the scripts for `/usr/bin` or wherever are very simple and only call a `.run()` or similar on a module. YMMV.

However it's probably a good idea to be a bit more flexible about what is included and excluded, currently a bunch of things are hardcoded. I've added a sub-issue for this on `prospector`, the underlying tool here: https://github.com/landscapeio/prospector/issues/26

**Comment by ssokolow** [comment]
@carlio

That's what `console_scripts` does. You feed it something like `json.tool:main` and it auto-generates a short script to import `json.tool` and call the `main` function inside it.

...of course, as I mentioned, it comes with additional portability helpers like generating a `.exe` wrapper for windows so typing the extensionless name in `cmd.exe` works without editing `PATHEXT`.

**Comment by carlio** [comment]
@ssokolow Oh, ok, thanks for telling me. I have to confess, I haven't delved into the soup of setup/distutils too much so I am probably very out of date in my approach.

**Comment by carlio** [comment]
I'm on a ticket closing binge so I'll close this one because it is covered in https://github.com/landscapeio/prospector/issues/69
