### ISSUE TITLE
Empty branches get a 100 % rating

### ISSUE THREAD

**Issue by Bengt** [landscapeio/landscape-issues#38]
I have an empty master branch, which gets a rating of 100 %. That does not make much sense to me. On the one hand, there are 0 errors/warnings/smells, but on the other hand, there are also 0 lines of python code that could be imperfect. Perhaps landscape should add a extra state for these situations. A pythonic choice would be to name this health rating `None`, but `unknown` would probably more human-readable.
-   The github tree view for the empty branch:  
  https://github.com/cigroup-ol/metaopt/tree/master
-   The landscape page for the empty branch:  
  https://landscape.io/github/cigroup-ol/metaopt/10>

**Comment by carlio** [comment]
Empty branches now have special handling to ensure they don't show up as 100%
