### ISSUE TITLE
Add a way to ignore flake8 errors

### ISSUE THREAD

**Issue by dbrgn** [landscapeio/landscape-issues#39]
There should be a way to ignore specific error codes for the flake8 checks (in my case it's `E124 E126 E127 E128`). This can be done by using the flake8 `--ignore` flag.

**Comment by peterjc** [comment]
I was looking for the same thing, although we currently use `pep8` at the command line and ignore `E121`, `E122`, `E123`, `E124`, `E125`, `E126`, `E127`, `E128`, `E129`, `E131`, `E501`.

i.e. It would be nice to pass this ignore list (or white list) to all relevant tools which understand this naming convention.

**Comment by carlio** [comment]
I (finally) set up a documentation page to cover this: https://docs.landscape.io/suppressing.html
