### ISSUE TITLE
Feature Request: Improved Repo Management

### ISSUE THREAD

**Issue by beittenc** [landscapeio/landscape-issues#4]
When I first learned about landscape.io, I forked a couple repos so I could run the tools against them to satisfy my own curiosity. I've since deleted those repos, but I can't find any way to tell landscape to stop checking them. It would be awesome if I could do so without deleting my whole account. SImilarly, I've created some new repos and cannot find a way to refresh my repo list so begin checking those.

**Comment by carlio** [comment]
There was a bug where repositories which disappeared on GitHub were not properly deleted on Landscape, which I have now fixed! Thanks for the bug report :)  Hopefully if you check now you will no longer see the deleted repositories on Landscape.

The repository list refreshing happens automatically right now, but only every hour or so. I will put a button somewhere to enable you to trigger a sync.

**Comment by beittenc** [comment]
Auto-repository clearing works for me. I'm also happy with an automated sync every hour or so, but it would be helpful if there was some indication that's what's happening. This could be as simple as a note or something a little more involved like "Next refresh in around 15 minutes." I think this would satisfy the desire for most people and also prevent people from spamming a refresh button and eating a bunch of resources.

**Comment by carlio** [comment]
There is now a 'Synchronise with GitHub' button on the dashboard to schedule an immediate sync
