### ISSUE TITLE
badges not working

### ISSUE THREAD

**Issue by glaslos** [landscapeio/landscape-issues#42]
See example here: https://gist.github.com/glaslos/60b03617d6b89d1813ed

**Comment by carlio** [comment]
Hi @glaslos - in that particular example you're missing the substitution reference - it works for me if I do this: https://gist.github.com/carlio/849e9e4bee5381fafeb8 . Are you having this issue as part of a larger document elsewhere?

**Comment by glaslos** [comment]
Perfect, my fault.
