### ISSUE TITLE
PyQt support

### ISSUE THREAD

**Issue by ColinDuquesnoy** [landscapeio/landscape-issues#45]
When using landscape.io for a PyQt based project we get a lots of errors related to missing members. This happens because PyQt4 cannot be installed using pip.

This problem will also happen with most python bindings that require to install a C++ library (pyzmq, pysfml,...).

My suggestion is to add the ability to install dependencies using apt-get (or any other package manager if the landscape.io virtual machines do not run on Ubuntu). Maybe something similar to how Travis-CI let us install dependencies.

**Comment by baudren** [comment]
As far as I can tell, it also seems not to work for `PySide` projects, though it is available from pip. I am not sure if pip has anything to do with it. Probably the depency on C++ libraries might be a problem, but not for every library.

For instance, in one of my project, I am using `pypandoc`, which also requires `pandoc` to be installed, and yet Landscape detects the proper members of `pypandoc` module.

**Comment by js850** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ssokolow** [comment]
If I remember correctly, this is what the `extension-pkg-whitelist` option is for in `.pylintrc`.

You give it a list of packages it can't see inside and it ignores them. (Last I checked, the default value was `gtk,pango`)
