### ISSUE TITLE
landscape yaml and ignored paths issue

### ISSUE THREAD

**Issue by shidarin** [landscapeio/landscape-issues#46]
Sometime between the 10th of May and the 29th of May, the following became a configuration error:

```
ignore-paths:
    - setup.py
    - cdl_convert/__init__.py
    - docs
    - tests
ignore-patterns:
```

It won't let ignore-patterns be blank, throwing an error about how `ignore-patterns` cannot be set to (None). At the same time, it started ignoring my `ignore-paths`, and began parsing `setup.py`, and the `__init__.py` file. It's still ignoring `docs/` and `tests/`.

McCabe now refuses to run, saying an exception was raised (Will not say exception).

I removed `ignore-pattern` from my landscape.yaml file, but `setup.py` and `__init__.py` are still being listed in the reports, and McCabe still fails to run.

[Here's](https://landscape.io/github/shidarin/cdl_convert/66) a landscape report generated after I fixed the config file.

Thanks!

-Sean

Of course, since McCabe flags several of my more complicated functions, I'm quietly enjoying it's torment.

**Comment by carlio** [comment]
Thanks for the bug report.

I updated the config parsing a little to handle the empty lists. For what it's worth, you can also just omit `ignore-patterns` and it'll default to an empty list.

I also tracked down the issue with McCabe, which I am sure you will be pleased to here!
