### ISSUE TITLE
Incorrect warning on sphinx comments

### ISSUE THREAD

**Issue by dnephin** [landscapeio/landscape-issues#47]
Can be seen here: https://landscape.io/github/dnephin/PyStaticConfiguration/1/modules/staticconf/loader.py#L251

Sphinx allows you to document constants and (and fields, etc) by putting a docstring after them, but this is being reported as `String statement has no effect`.

**Comment by carlio** [comment]
Hi @dnephin, I've fixed that and upgraded a bunch of dependencies at the same time. While you can see at https://landscape.io/github/dnephin/PyStaticConfiguration/3/modules/staticconf/loader.py#L251 that the error you reported has gone, it seems I introduced a few other over-zealous checks, which I'll look into fixing!
