### ISSUE TITLE
Using six.moves causes a warning

### ISSUE THREAD

**Issue by dnephin** [landscapeio/landscape-issues#48]
Can be seen here: https://landscape.io/github/dnephin/PyStaticConfiguration/1/modules/staticconf/loader.py#L59

Of course it's redefining a built-in, it's for python 3 compatibility!

**Comment by astrofrog** [comment]
I have this issue too!

**Comment by mdshw5** [comment]
I also have this message quite a bit, but in my mind it's not so much an issue as a clear warning.
