### ISSUE TITLE
Feature Improvement: meaningful errors/smells explanations

### ISSUE THREAD

**Issue by caiobegotti** [landscapeio/landscape-issues#5]
This is a fantastic tool for people learning Python who sometimes don't know if this or that is good code, but the errors and smells explanations are far from understandable by common lay men (like myself). It would be nice to at least have a link at the end of the explanation pointing to some place telling me more about it, as sometimes I don't even know what to look for on Google to better understand the problem.

**Comment by carlio** [comment]
You're right, some of the explanations are not particularly easy to follow. I plan to improve this, and also include suggestions of how to fix the particular problem - watch this space!

**Comment by pennyarcade** [comment]
Both pylint and pep8 support putting out error explanations. pep8 does this by default, pylint has to be asked to generate documentation or for a special error code.
You could just display those :)
