### ISSUE TITLE
pylint failed to run, health: 100%

### ISSUE THREAD

**Issue by rshipp** [landscapeio/landscape-issues#50]
See https://landscape.io/github/george2/sundara/23 and https://landscape.io/github/george2/sundara/23/diff. No information is given about why pylint failed, and the repository health is set to 100% instead of something like `unknown` or `error`.

Possibly related to #38?

**Comment by rshipp** [comment]
Looks like this is part of some larger issue, as even Landscape.io's [own repos](https://landscape.io/github/landscapeio/pylint-common/6) are failing right now.

**Comment by carlio** [comment]
Not quite sure what happened here, I fixed a different issue and this one is now gone. I think it was a file permissions error, oddly. Sorry about that!
