### ISSUE TITLE
Badges should accept shields.io style parameters

### ISSUE THREAD

**Issue by luanfonceca** [landscapeio/landscape-issues#51]
As i see, the Landscape uses shields.io to render his badge, but the Landscape doesnt accept all the options of the shields.io, see:
[![Code Health](https://landscape.io/github/luanfonceca/speakerfight/master/landscape.png?style=flat)](https://landscape.io/github/luanfonceca/speakerfight/master)

But if i use (in the hardcoded way) the shields.io url and pass the `style=flat` it works:
[![Code Health](https://img.shields.io/badge/health-85%25-brightgreen.svg?style=flat)](https://landscape.io/github/luanfonceca/speakerfight/master)

Thanks in advance.

**Comment by carlio** [comment]
This is now done! You can append `style=flat` or any other value that shields.io accepts now.
