### ISSUE TITLE
Server Error #500 on several pages

### ISSUE THREAD

**Issue by pennyarcade** [landscapeio/landscape-issues#52]
the following pages do not work for me:
- https://landscape.io/github/.../4/diff
- https://landscape.io/github/.../4/messages/error
- https://landscape.io/github/.../4/messages/smell
- https://landscape.io/github/.../4/messages/style
- https://landscape.io/github/.../4/messages/<number>

So effectively there is no diagnostics for me to fix my code, only summary works.

**Comment by LuisAlejandro** [comment]
This is happening for me as well:

https://landscape.io/github/tribusdev/tribus/69/diff

**Comment by pennyarcade** [comment]
Hello

Workaround: Don't have source files larger than 1 MB.

Works for me now. I'll leave the issue open since the #500 Errors have to be fixed anyway :)

**Comment by carlio** [comment]
Just to expand on this a little: The GitHub API call that Landscape uses to fetch file contents has a 1MB limit. I will update the code to fall back to the [Blob API](https://developer.github.com/v3/git/blobs/) when necessary. Hopefully not many people have a python file more than 1MB in size though!

**Comment by mottosso** [comment]
Happening here too. There might be large files in the git history, but currently I don't think there is anything above 1 mb.

https://landscape.io/github/abstractfactory/publish

**Comment by carlio** [comment]
These all seem to be fixed now.
