### ISSUE TITLE
Landscape reporting/marking when it can't import python modules

### ISSUE THREAD

**Issue by brifordwylie** [landscapeio/landscape-issues#54]
Landscape is reporting unable to import zerorpc see this link for an example:
https://landscape.io/github/SuperCowPowers/workbench/445/diff

I'm assuming that's because zerorpc isn't part of the standard module packages? I have a bunch of non-standard modules, so interesting that it picks up on this one in particular.

**Comment by carlio** [comment]
There is an update in the works which changes how Landscape runs the checks, which will involve completely standalone virtualenvs and Docker and all that fancy stuff. I expect this will fix a lot of things related to third-party dependencies! Hopefully it'll be available in a couple of weeks.

**Comment by pennyarcade** [comment]
Will it be compatible to Shippable.com's requirements.txt? That would be wonderful and I could use one config for both :)

**Comment by carlio** [comment]
@pennyarcade yes, it should "just work" with a requirements.txt file, although 1) it doesn't quite work with libraries requiring system-level packages, such as lxml, and 2) the original reported error is a slightly different bug to what I thought. I'm going to do some "code sprinting" this weekend to get through this and several other older issues, I will update you soon!

**Comment by carlio** [comment]
The installation of requirements has been around for a little while now, and there have been several improvements in detection and installation :)
