### ISSUE TITLE
Prospector should detect urwid and filter PyLint complaints appropriately

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#55]
Whenever I use Landscape on a project built on urwid (a TUI library sort of like GTK+ for the console), I end up having to flood my code with lines like these:

```
# pylint: disable=too-many-public-methods
# pylint: disable=too-many-arguments,unused-argument
```

Obviously, this is irritating, counterproductive, distracting, and a waste of time.

**Comment by ssokolow** [comment]
In fact, now that I've done some complaint squashing using Prospector, I see it's even worse than that.

Check out this result here.

https://landscape.io/github/ssokolow/lap/2/modules/lap/ui/urwid_chooser.py

Those are all spurious errors and, when run locally, Prospector doesn't complain about any of them, so I have no idea what the PyLint/PyFlakes codes are to manually ignore them.

**Comment by carlio** [comment]
I suspect this is because you run prospector in your own virtualenv, which means you have all of those dependencies on your path. Currently Landscape just runs prospector on the bare repository, which means the underlying tools aren't as good at handling inference. There is an update in the works in which Landscape will start using virtualenvs per project and installing dependencies (as far as possible), which I hope will solve issues like these and improve the inference and error detection.

**Comment by carlio** [comment]
Having said that, there's still some additional work required to handle libraries which require system packages to be installed like PIL or (I suspect) urwid. That wouldn't be a huge leap from the new setup though.

**Comment by ssokolow** [comment]
Actually, urwid's only required dependencies are Python itself and a POSIX-compliant OS. Everything else [is optional](http://urwid.org/).

(In fact, even if you have ncurses installed, it prefers its internal ncurses clone unless explicitly told otherwise.)

**Comment by carlio** [comment]
The feature which actually installs project requirements was rolled out recently and it seems to have fixed most of this problem - https://landscape.io/github/ssokolow/lap/8

**Comment by ssokolow** [comment]
Keep in mind that I've got two noteworthy classes in there, one which is still complaining about having inherited too many public methods and the other which has a pragma to suppress that complaint.

Of course, that could just be stale data for all I know. I can't find any kind of "re-run checks on the same code because Landscape has changed" button.

**Comment by carlio** [comment]
Yes, that's why the issue is still open! I'll see if I can get McCabe to not warn based on inheriting too many methods.

**Comment by ssokolow** [comment]
Ahh, point. I'm a bit dozy and I didn't really notice that you said "most". Thanks.
