### ISSUE TITLE
doesn't list organization repositories

### ISSUE THREAD

**Issue by twatteyne** [landscapeio/landscape-issues#58]
Hi,
I'd like to use landscape on the `openwsn-berkeley/coap` repo. This is part of the `openwsn-berkeley` GitHub organization, which I'm a (public) member of.
I just signed into landscape with my GitHub account, but landscape doesn't list any of the repositories of the `openwsn-berkeley` organization.
Thomas

**Comment by carlio** [comment]
Hi @twatteyne - it seems like the syncing code wasn't working at the time you signed up, so Landscape didn't correctly connect your organisations. It should work now, please let me know if it doesn't!

**Comment by twatteyne** [comment]
It works, beautiful. Thanks for the quick action!
