### ISSUE TITLE
Feature Request: possibility to add/remove ignore flags to avoid false positives

### ISSUE THREAD

**Issue by caiobegotti** [landscapeio/landscape-issues#6]
I'm not sure if that's a big problem and I didn't look the backend code to check it but does it check against Python 3 primarily? Some of my codes are supposed to be "old" Python 2 stuff for real and I don't know if I'm seeing errors not exactly written by me or just the backend flagging them because my code "should" be Python 3.

**Comment by carlio** [comment]
This is next on my list. I want to make a really simple, interactive way to mark errors as "not really an error", since it's very hard to be 100% accurate when analysing Python code because it is so dynamic in nature.

**Comment by dbishop** [comment]
I'm not sure the best way to address my particular problem (see below), but being able to add some special "exception" comment on the particular line in question would be sufficient... something like "# noqa".

I have a class which inherits from (only) `gevent.queue.Queue` and whose constructor calls `self.put(...)`.  This is erroneously getting flagged as a Nonexistent member.  See https://landscape.io/github/swiftstack/ssbench/1/messages/50

Is there currently any mechanism for providing hints or exceptions to the checker?  Is there something about gevent.queue.Queue in particular which confuses the checking tooling (Prospector, pylint, etc.)?

**Comment by carlio** [comment]
Hi @dbishop . You can add `# pylint: disable:E1101` at the end of that line or on the line above.

That's not particularly friendly and I want to make it easier to ignore and add such exceptions in the future.

You can install and run [prospector](https://github.com/landscapeio/prospector) locally if you like - that is what Landscape uses 'behind the scenes', albeit with some default config. `prospector -DT --path .` will show you a similar output to the Landscape web UI

**Comment by ssokolow** [comment]
@carlio Actually, it's `# pylint: disable=E1101`. 

Using a colon just silently fails in my offline copy of prospector and produces this error when PyLint is called directly:

```
Unable to consider inline option u'disable:W0613' (bad-inline-option)
```

Also, I hope your plan to add exceptions still involves storing them in the project repository. I value data portability highly and prefer to keep everything in a neat, unified package. (In fact, I've been considering ditching GitHub Issues for my projects because it's the only GitHub Component that you can't fork/backup/export with a simple `git clone`)

**Comment by carlio** [comment]
Finally added some proper documentation on this: https://docs.landscape.io/suppressing.html
