### ISSUE TITLE
stuck for hours in "Scheduling first check"

### ISSUE THREAD

**Issue by twatteyne** [landscapeio/landscape-issues#60]
I set up https://landscape.io/repository/58890/status
to run on https://github.com/openwsn-berkeley/coap.

The status page has been stuck on "Scheduling first check" for hours.

I have a `.landscape.yaml` file to the repo hours ago. Do I need to do something to get the job to run?

**Comment by carlio** [comment]
Hi! I just fixed this (sorry it was late, Europython happened amongst other things). 

It turns out there was a worker that did not restart properly, so was using old code. Sorry about that.

**Comment by twatteyne** [comment]
That's absolutely beautiful, thanks a million. Everything seems to work fine now.
I hope you enjoyed Berlin!
