### ISSUE TITLE
Repository missing in "add repository" dialog

### ISSUE THREAD

**Issue by cdeil** [landscapeio/landscape-issues#61]
If I go to https://landscape.io/repository/add and search for "astropy", I see e.g. `cdeil/astropy-helpers` and a few other repos, but `cdeil/astropy` is missing.

Is this a bug?
What do I have to do to activate landscape for the `cdeil/astropy` repo on Github?

**Comment by carlio** [comment]
Hi @cdeil . Is this still happening? I checked the database and as far as I can tell, you should be able to see and start that repository. It could be that some state was re-synchronised in the last few days which fixed the issue.

**Comment by cdeil** [comment]
Still the same problem ... I just now re-did the search and took this screenshot:

![screen shot 2014-07-27 at 21 17 19](https://cloud.githubusercontent.com/assets/852409/3714898/d2097c44-15c2-11e4-960f-fc46231e17aa.png)

**Comment by kdavies4** [comment]
I have the same problem. If I go to https://landscape.io/repository/add, it seems that the list is outdated. I see at least one repo that I deleted today but one I added several days ago (`kdavies4/natu`, the one I want to link with landscape.io) is missing. I've tried syncing [my GitHub account](https://github.com/kdavies4) several times.

**Comment by kdavies4** [comment]
In my case, I found that the project wasn't classified as Python, so I had to click Filter->Language->Everything.

**Comment by cdeil** [comment]
@kdavies4 Thanks!!!

Somehow I completely missed that there's filters on the left side ... after I change `Language` from `Python` to `Everything`, then `cdeil/astropy` does show up (because it's classified as a C project).
So there probably never was an issue with the site ... closing now.
