### ISSUE TITLE
SQLAlchemy models not having a query() attribute

### ISSUE THREAD

**Issue by hvdklauw** [landscapeio/landscape-issues#63]
In my case I'm using the Flask-SQLAlchemy package

**Comment by hvdklauw** [comment]
So maybe we need a thing just like the django thing to ignore these specific errors

**Comment by carlio** [comment]
Yes, that's probably the case. This probably requires a new `pylint-sqlalchemy` plugin.

**Comment by hvdklauw** [comment]
On second thought, it might be an issue with Flask.

Flask extensions are imported from flask.ext.\* while they actually reside in flask_*, can we somehow tell pylint to look there instead? That will resolve most of the false positives.

**Comment by carlio** [comment]
It turns out someone already asked that question: https://bitbucket.org/logilab/pylint/issue/95/how-can-i-write-a-plugin-to-change-imports 

The answer is currently 'no' but it is being worked on.

**Comment by shortdudey123** [comment]
Doesn't look like much has happened on this.  I am unable to use landscape.io with my flask projects right now.  Any suggestions on workarounds?

```
from flask.ext import restful
 No name 'restful' in module 'flask.ext'
```

**Comment by teleyinex** [comment]
Here I've the same issue. With Flask you've lots of issues due to the extensions ;-) My solution, ignore them as I test the code extensively. However, this is suboptimal, and a better solution from prospector should be used ;-)

**Comment by kxxoling** [comment]
Same issue here too.

**Comment by jschaf** [comment]
I made a pylint plugin that fixes the `flask.ext` import errors.  See https://github.com/jschaf/pylint-flask.  I haven't found anything for SQLAlchemy.

**Comment by teleyinex** [comment]
@jschaf great! Now they should include it in prospector and landscape :-)

**Comment by carlio** [comment]
@jschaf @teleyinex On it :)

**Comment by teleyinex** [comment]
woot!!!!!
