### ISSUE TITLE
Potential glitch in the score calculation

### ISSUE THREAD

**Issue by ssokolow** [landscapeio/landscape-issues#65]
Take a look at this commit. I made no changes to the code (just a docstring edit) and Landscape agrees that nothing relevant changed, but my code health dropped by 1%.

https://landscape.io/github/ssokolow/fastdupes/8/diff

**Comment by carlio** [comment]
I've changed the display a little now so if it's less than 1% change it will display more significant digits. I know the drop of '0.07%' is a bit silly but on the other hand, if the score doesn't change when errors are fixed, that's a bit silly too.
