### ISSUE TITLE
My public repository isn't listed for Add

### ISSUE THREAD

**Issue by mauler** [landscapeio/landscape-issues#66]
Hey,

I have this repository:

https://github.com/mauler/django-grappelli-extensions

But it doesn't show on landscape.io to be registered.

I don't know if the reason is that the original name of the repository was django-grappelli-navbar and then I renamed it to django-grappelli-extensions

Thanks,
Paulo.

**Comment by carlio** [comment]
Hi @mauler , can you check to see if it is there if you use the 'Everything' filter (see also bug #61)? GitHub classifies it as a CSS repository rather than a Python one, so Landscape hides it by default.
