### ISSUE TITLE
Python files not properly recognized

### ISSUE THREAD

**Issue by nschloe** [landscapeio/landscape-issues#67]
The project [BetterBib](https://landscape.io/github/nschloe/betterbib/1) is mainly composed of one Python file. landscape.io however doesn't seem to recognize that correctly, cf. https://landscape.io/github/nschloe/betterbib/1.

![landscape](https://cloud.githubusercontent.com/assets/181628/4081862/ab9cd03c-2eeb-11e4-8071-57e3a8d1cb24.png)

**Comment by carlio** [comment]
This is because the file doesn't have a `.py` extension, which is currently the only way it attempts to detect Python files.

**Comment by carlio** [comment]
I'm going to move this issue onto [prospector](https://github.com/landscsapeio/prospector) as this is where the detection of python files is done.

See https://github.com/landscapeio/prospector/issues/69
