### ISSUE TITLE
Repos with capital initials don't show in the add repo filter

### ISSUE THREAD

**Issue by hugovk** [landscapeio/landscape-issues#68]
Precondition:
You have a repo that begins with a capital letter
1. Go to https://landscape.io/repository/add
2. Start typing the name of the repo

Expected result:
The repo shows up in the filtered list

Actual result:
It doesn't show up. Only those beginning with lower case initials

**Comment by carlio** [comment]
Hi, thanks for the bug report, this is now fixed and the searching is properly case sensitive.

By the way thanks for Pillow, it's a fantastic project and has saved me so much time!

**Comment by hugovk** [comment]
Glad Pillow is useful! I'm just one of many contributors. And thanks for the quick replies!
