### ISSUE TITLE
A branch being checked is shown as not yet checked

### ISSUE THREAD

**Issue by hugovk** [landscapeio/landscape-issues#69]
1. Go to a branch page that's not yet been checked

->

> No Checks Yet
> 
> The branch foo has not been checked yet.
1. "Click Check Now"

->

> Running...
> 
> Check #22 is currently queued .
> 
> Committer: Waiting...
> Commit Hash: Waiting...
> Commit Message: Waiting...
> Waiting...

Note the /X number at the end of the URL.
1. Go back to the repo overview. From the dropdown select the same branch.

Expected result: See the waiting page.

Actual result: See "No Checks Yet" page. This means you might click "Check Now" again and start a new check, but really if you change the URL to /X where X is the last check number, you see the previous check running. This problem means you might go in a loop and add several repeated checks on the same commit. It's unnecessary and confusing.

**Comment by carlio** [comment]
Agreed, the logic was a bit silly here - it only checked to see if there were successful checks before deciding to show the "check now" dialog. This is now fixed.
