### ISSUE TITLE
code quality analysis on pull requests?

### ISSUE THREAD

**Issue by js850** [landscapeio/landscape-issues#71]
Is it possible to get a report from landscape on pull requests?  I feel like this should already be available, but I couldn't figure out how to do it.

**Comment by hugovk** [comment]
Yes, it would be really useful to be able to give feedback about pull requests, for example to fix some things Landscape discovers, before merging.

**Comment by shortdudey123** [comment]
:+1: to this request

**Comment by teleyinex** [comment]
:+1: It would be great to get a comment like Coveralls does.

**Comment by hugovk** [comment]
Use GitHub's Status API for something like this:

![](https://cloud.githubusercontent.com/assets/483/5332863/0f58f9b6-7e1a-11e4-9884-e362ec566f2b.png)

See https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

**Comment by teleyinex** [comment]
:+1:

**Comment by carlio** [comment]
Hi all! You can now have lovely lovely comments on your pull requests!

For now it's still a bit experimental so I won't enable it for everyone by default, but you can [go to your settings page](https://landscape.io/preferences/) to enable it for each organisation you are a part of.

If you have any problems with it please file a bug report, that would be very helpful.

@hugovk I've looked into the status API and the problem right now is that it requires either 'public_repo' scope (which includes write access to repositories) or 'repo:status' scope (which gives read/write access to public and private repositories, but only for statuses). When I figure out the best choice for that I'll integrate it into the status API as an optional extra.

**Comment by teleyinex** [comment]
I've just tried and got a 500 from your server :-)

I'm enabling the comments for PyBossa, without any private user. Should we add one?

**Comment by carlio** [comment]
@teleyinex you only need a private user if you have private repositories. The bug was related to that though, it choked when there was no option for commenting! I've (hopefully) fixed it now, if you want to try again.

**Comment by hugovk** [comment]
Thanks!

**Comment by teleyinex** [comment]
@carlio now it saved my preferences. Thanks for the fix. I'll let you know if we don't get any comments on our PyBossa organization!!!

**Comment by carlio** [comment]
This totally works, I'm just rubbish at closing tickets. I'll open a new one for the status API feature.

**Comment by ragv** [comment]
@carlio Sorry for piggybacking on an old thread... We have enabled comments for our repo at scikit-learn/scikit-learn (Refer https://github.com/scikit-learn/scikit-learn/pull/4372#issuecomment-78054010).

But the landscape-bot is yet to comment on status of the check... could you kindly take a look into it? Thanks!
