### ISSUE TITLE
Flat shield(badge) style

### ISSUE THREAD

**Issue by tlaundal** [landscapeio/landscape-issues#74]
I think it should be possible to have health shields in flat style.
This could be made possible by simply passing the `?style=style` parameter on to the `img.shields.io` link, or have different URLs for each style. A pull request could also be made to (shields)[https://github.com/badges/shields] itself, so the URL could be something like `img.shields.io/landscapeio/user/repo/shield.svg?style=style`

**Comment by carlio** [comment]
This is now done! You can append `style=flat` or any other value that shields.io accepts now.

(See also #51)
