### ISSUE TITLE
Not running for recent commits

### ISSUE THREAD

**Issue by hugovk** [landscapeio/landscape-issues#77]
https://landscape.io/github/python-pillow/Pillow shows last master commit from 3rd October, but the last one was on the 15th with lots in between.

Same for my fork -- https://landscape.io/github/hugovk/Pillow -- shows 3rd October, but last was 13th Oct with many in between.

**Comment by carlio** [comment]
Hi, sorry I missed this. The checks are running again - they were failing unfortunately, but it's back now!
