### ISSUE TITLE
Python 3.x annotations seems to be not reconized

### ISSUE THREAD

**Issue by buxx** [landscapeio/landscape-issues#78]
Python 3.x annotations seems to be not reconized ([PEP 3107](http://legacy.python.org/dev/peps/pep-3107/)). Exemple with [this landscape error](https://landscape.io/github/buxx/synergine/2/modules/synergine/src/core/ActionManager.py) :

``` python
def get_steps_for_actions(self, actions: list):
```

on the `: list` annotation.

**Comment by ids1024** [comment]
See #32.

**Comment by kkamkou** [comment]
:+1:

**Comment by buxx** [comment]
Note: i unsubscribe of this issued, i changed to scrutinizer-ci.
