### ISSUE TITLE
Python 3.x class declaration not reconized

### ISSUE THREAD

**Issue by buxx** [landscapeio/landscape-issues#79]
[Python3.x class declaration](https://docs.python.org/3.4/tutorial/classes.html) `class Foo:`  seems not reconized: [exemple](https://landscape.io/github/buxx/synergine/2/modules/synergine/lib/factory/factory.py#L1)

**Comment by carlio** [comment]
This is basically because Landscape doesn't handle Python3 at all yet. There is an outstanding issue about that: #32 . Once Python3 is properly supported, then this issue will go away, so I'll close this issue as a subset of #32
