### ISSUE TITLE
Bug: User/org name link in breadcrumbs is broken

### ISSUE THREAD

**Issue by jnovinger** [landscapeio/landscape-issues#8]
In the breadcrumbs near the upper-right of the window, the link to the user/org appears to be broken.

Expected:https://landscape.io/github/mozilla
Actual: https://landscape.io/github/mozilla/solitude/master#

See screenshot:

![landscape hosted continuous python code metrics - google chrome_474](https://f.cloud.github.com/assets/103499/1545827/18552a64-4d7c-11e3-9f81-7a202bd384c1.png)

**Comment by carlio** [comment]
The breadcrumbs have disappeared as part of the redesign, so this is no longer an issue.
