### ISSUE TITLE
when I try to add a repository it spins for a long time.

### ISSUE THREAD

**Issue by dnozay** [landscapeio/landscape-issues#80]
When I try to add a repository it spins for a very long time, and tries to load https://landscape-io.s3.amazonaws.com/third/icheck/skins/minimal/grey.png followed by https://www.google-analytics.com/collect?...etc. I have a lot of forks. Sometimes it fails and crashes the browser window.

**Comment by carlio** [comment]
Is this still a problem? I did a lot of fixing of performance so hopefully it is okay now. Please reopen if you still have problems.
