### ISSUE TITLE
Nested classes

### ISSUE THREAD

**Issue by berndca** [landscapeio/landscape-issues#82]
I'm using nested classes, like shown the in example code below:

```
class Model(object):
    test = True


class AttributeModel(Model):

    class Meta:
        meta_prop = 42

    def __init__(self):
        super(AttributeModel, self).__init__()
```

The analysis seems to ignore the fact that Meta is a nested class and considers **init** to be a method of Meta. I'm getting the error: "Use of super on an old style class". However **init** is a method of AttributeModel which is not an old style class, instead.

**Comment by carlio** [comment]
Hi @berndca - I assume you're referring to https://landscape.io/github/berndca/xmodels/1/modules/xmodels/models.py#L388 ?

If so, there is a few issues currently with six's `with_metaclass` decorator which I'm trying to work out. Inheritance from classes returned from functions is a bit broken in general!

Thanks for the report, I'll update when I figure out how to properly handle the `with_metaclass`.

(This is also related: https://landscape.io/github/berndca/xmodels/1/modules/xmodels/models.py#L255)
