### ISSUE TITLE
Issues with dynamically created attributes

### ISSUE THREAD

**Issue by astrofrog** [landscapeio/landscape-issues#84]
Here are examples of 'errors' that should not really happen:

![screen shot 2014-11-05 at 11 48 45 pm](https://cloud.githubusercontent.com/assets/314716/4927717/14c4288e-653e-11e4-9b01-740b1d6646b8.png)

`six.add_metaclass` does exist. In the following case, `u.deg` is the same as `astropy.units.deg` and `deg` is created at import time.

![screen shot 2014-11-05 at 11 50 38 pm](https://cloud.githubusercontent.com/assets/314716/4927746/4a9e405c-653e-11e4-9932-337363345675.png)

Is there a way to whitelist such cases?

**Comment by cdeil** [comment]
@astrofrog The "Module 'astropy.units' has no 'deg' member" error is generated by [pylint](http://www.pylint.org/).

The way to pass configuration options to pylint is via the `.prospector.yaml` file:
http://prospector.readthedocs.org/en/latest/profiles.html#enabling-and-disabling-messages
(see #83 for the question what goes in `.landscape.yaml` vs. `.prospector.yaml`)

With this `test.py` file:

``` python
from astropy import units
print(units.degree)
```

you'll get

``` bash
$ prospector test.py
...
test (test.py):
    L2:12 None: pylint - E1101
    Module 'astropy.units' has no 'degree' member
```

Dynamically-generated attributes are the issue for at least the `astropy.units.deg` error ... they defeat static code analysis: http://stackoverflow.com/a/18712867/498873

One option is to use the ignored-classes`option from`pylint`, which apparently also can be used for Python modules or packages:

``` bash
$ pylint test.py --ignored-classes=astropy.units
```

A better option would be to tell pylint to actually import and dynamically generate the members before doing code analysis for `astropy.units`. I'm not sure this is possible ... haven't looked yet, but this might be relevant:
http://www.logilab.org/blogentry/78354

**Comment by astrofrog** [comment]
@cdeil - thanks for looking into this! If it is a pylint error, it's also possible to add pylint directives at the top of a Python file, e.g.:

```
# pylint: disable=wildcard-import, method-hidden
# pylint: enable=too-many-lines
```

I will check if it's possible to add a directive to ignore this specific error (e.g. using ignored-classes)

**Comment by cdeil** [comment]
It would be nice to configure this in `astropy.units` only and get rid of the E1101 error in all affiliated packages automatically. Thanks for looking into this!

**Comment by mdshw5** [comment]
+1 for ignored-classes as a directive in the file header
