### ISSUE TITLE
Issue with np.meshgrid

### ISSUE THREAD

**Issue by astrofrog** [landscapeio/landscape-issues#85]
I don't understand the following error:

![screen shot 2014-11-05 at 11 51 48 pm](https://cloud.githubusercontent.com/assets/314716/4927758/61686344-653e-11e4-813e-6a005367898d.png)

I'm surprised landscape even tries to guess anything here - how does it know what `np.meshgrid` returns? (this is correct code by the way)

**Comment by cdeil** [comment]
@astrofrog Where did you get this "smell"?

The first step would be to identify which tool incorrectly triggers on this code.
With this example:

``` python
import numpy as np
x = np.linspace(10)
y = np.linspace(10)
Y, X = np.meshgrid(y, x)
```

I don't see that message:

``` bash
$ prospector test.py 
Check Information
=================
       Started: 2014-12-01 10:25:28.396480
      Finished: 2014-12-01 10:25:29.092324
    Time Taken: 0.70 seconds
     Formatter: text
    Strictness: medium
Libraries Used: 
     Tools Run: dodgy, frosted, mccabe, pep8, pyflakes, pylint
      Adaptors: common-plugin, profiles:strictness_medium,no_doc_warnings,no_test_warnings
 Message Found: 3


Messages
========

test (test.py):
    L3:7 None: pylint - E1101
    Module 'numpy' has no 'linspace' member

test (test.py):
    L4:7 None: pylint - E1101
    Module 'numpy' has no 'linspace' member

test (test.py):
    L6:10 None: pylint - E1101
    Module 'numpy' has no 'meshgrid' member
```

**Comment by astrofrog** [comment]
@cdeil - see the bottom of this page:

https://landscape.io/github/astrofrog/wcsaxes/9/messages/smell?page=4#errors

Also, in your example the three errors you get are not good since they are incorrect, right?

**Comment by astrofrog** [comment]
Looks like this warning disappeared in a more recent build. It might be fixed?

https://landscape.io/github/astrofrog/wcsaxes/12/modules/wcsaxes/transforms.py

**Comment by cdeil** [comment]
I think `pylint`, `prospector` and some other moving parts get updated once in a while ... not sure why this warning disappeared.
I also didn't track down why `pylint` gives `E1101` locally for me for `numpy.linspace` and `numpy.meshgrid` (probably dynamically generated on import) ... let's only focus on remaining issues that show up for Astropy or affiliated packages on landscape.io for now.

**Comment by astrofrog** [comment]
Since this is probably no longer relevant, I'll close this now
