### ISSUE TITLE
Hide repositories from Dashboard

### ISSUE THREAD

**Issue by gtback** [landscapeio/landscape-issues#86]
I am a member of several organizations with a large(ish) number of repos. It appears that any repo in any organization I have access to shows up on my dashboard. If possible, I would like to hide certain repos, or at least "pin" certain repos to the top, so I can see them without scrolling. I can disable checking by clicking the red X, but I presume that will prevent anyone else from seeing the results as well.

**Comment by carlio** [comment]
Hi @gtback , you're right, the red x cancels it for everyone (that should be made more clear).

Would you like to be able to filter by organisation and further by name instead of your proposed solution? I can also look into the pinning version too but it'd be a little harder to persist that.

**Comment by gtback** [comment]
Thanks, @carlio. Filtering by organization would be a good first step. That way I can "focus" on a particular organization at time. I still think it would be helpful to reorganize the dashboard a bit, so that I can see more than 4 repositories without scrolling.

**Comment by edmorley** [comment]
I'd love this too :-)

**Comment by carlio** [comment]
Finally implemented the "hiding from dashboard" feature :)

I'll look into "filter by organisation" now

**Comment by gtback** [comment]
Looks great, @carlio . Thanks!

**Comment by carlio** [comment]
Filtering by organisation now works too :beer:

**Comment by gtback** [comment]
:grinning: Thanks so much!
