### ISSUE TITLE
Django as requirement sometimes not installed correctly

### ISSUE THREAD

**Issue by carlio** [landscapeio/landscape-issues#88]
If you look at https://landscape.io/github/fsr-itse/EvaP/138/requirements and then https://landscape.io/github/fsr-itse/EvaP/143/requirements , it seems that Django was not installed correctly beginning around October 24th. This causes problems with inference, thus lowering scores.

**Comment by karyon** [comment]
this problem still persists and makes landscape practically unusable for us, a fix would be greatly appreciated.

**Comment by carlio** [comment]
I found the problem here, so you should be seeing this work now. Sorry for taking forever.

**Comment by karyon** [comment]
yes, it works now. i would close this if i could :)
