### ISSUE TITLE
404 for delta page

### ISSUE THREAD

**Issue by hugovk** [landscapeio/landscape-issues#91]
For example:
1. Go to https://landscape.io/github/python-pillow/Pillow/86
2. Click "No change, Score stayed the same, 1 new problem. 0 problems were fixed."

Expected:
See the delta page that shows the new/fixed problems.

Actual:
"404 The requested URL was not found"
https://landscape.io/github/python-pillow/Pillow/undefined

Same happens for earlier builds.

---

Bonus: 

Also, it'd be nice if the "No change, Score stayed the same, 1 new problem. 0 problems were fixed." hyperlinks were underlined on mouseover, like the other links. It's not immediately obvious it's clickable.

**Comment by carlio** [comment]
I fixed the URL now so the link will work at least. I'll look into how to make it more obvious it is clickable. Thanks!
