### ISSUE TITLE
Need payed subscription for public git repository?

### ISSUE THREAD

**Issue by pennyarcade** [landscapeio/landscape-issues#94]
Hello,

I get the following error on both of my public repositories:

"Checks for pennyarcade/py_pov are no longer taking place as the trial period has expired. Please purchase a plan to reactivate checks."

The help section states:
"Landscape is free for open-source repositories - that is, for publicly available GitHub repositories."

I didn't have activity on my repos for a while but I'd like to start again. Please help.

Btw: When I try viewing the payment plans I get an error 500...

Regards, Martin

**Comment by carlio** [comment]
Hi Martin,

This is just a display bug - the checks are still running and it is indeed free for open source repos. Check #2 just finished: https://landscape.io/github/pennyarcade/py_pov/2

At some point you signed up for a trial but the notification should not be displaying for public repos. I'll fix that to remove the error.

Cheers, Carl

**Comment by carlio** [comment]
Ok, that's now gone from public repositories. Thanks for pointing it out!
