### ISSUE TITLE
Include matplotlib on landscape.io

### ISSUE THREAD

**Issue by astrofrog** [landscapeio/landscape-issues#97]
At the moment matplotlib does not install correctly:

https://landscape.io/github/astrofrog/wcsaxes/18/requirements

Would it be possible to add it to the system installation of Python on landscape.io?

**Comment by carlio** [comment]
In general adding system requirements is probably a huge burden that would slow down many builds. I will come back to this in the future but for now (because I'm on a ticket closing binge) I'll close this as "probably not doable".
