### ISSUE TITLE
Diff shows message as being fixed when it's not

### ISSUE THREAD

**Issue by inglesp** [landscapeio/landscape-issues#98]
https://landscape.io/github/inglesp/fakerbase/3/diff/fixed says that `Class 'FakerbaseManager' has no '_FakerbaseManager__database' member` (fakerbase/__init__.py:37.15) was "fixed in this push", but it wasn't, and indeed it shows up at https://landscape.io/github/inglesp/fakerbase/3/messages/error.

**Comment by inglesp** [comment]
Let me know if you'd like a simpler repro scenario.

**Comment by carlio** [comment]
Fixed! Thanks :+1:
