### ISSUE TITLE
Delta error count error

### ISSUE THREAD

**Issue by kxxoling** [landscapeio/landscape-issues#99]
Every time I received mail like this got wrong count on delta percent. eg:

![2014-12-11 1 52 42](https://cloud.githubusercontent.com/assets/1227139/5389775/4d759a58-813d-11e4-8585-85fbfe376e81.png)

The former percent is 81%, so delta would be 19 but not 18.

**Comment by carlio** [comment]
I found the error, I was using `int(score)` in a few places to round instead of using `round`. The previous check should have been 82%, not 81% - which is now fixed: https://landscape.io/github/kxxoling/ac-sso-demo/4

Thanks for the bug report!
